### ISSUE TITLE
Get endorsement from original creator

### ISSUE THREAD

**Issue by athix** [Sorcery/sorcery#1]
While not technically necessary, it would be nice to get @NoamB's approval for moving Sorcery to this organization. Sorcery is still very much in use, but until it's moved to an organization it remains difficult to maintain.

@NoamB has been contacted by @arnvald and myself, but there has been no response yet as far as I'm aware.

**Comment by athix** [comment]
Pinged @NoamB on Facebook and Gitter today, will update issue if he responds.

**Comment by Ch4s3** [comment]
I think its pretty unlikely, he seem to have stopped doing open source for the last 2 years. While I agree that it would be nice, we should proceed as planned if we don't hear back.
