### ISSUE TITLE
Be more selective when resetting the session on logout

### ISSUE THREAD

**Issue by brendon** [Sorcery/sorcery#105]
As per: https://github.com/NoamB/sorcery/issues/671#issuecomment-361642349

Completely resetting the session on logout means that if one is also logged in using Devise, or in any way would like to keep certain session keys, they can't. They'll be logged out of Devise and all keys are reset.

I can see the advantage of doing so, but perhaps we could also make it an option that Sorcery is also selective about the keys it resets (only resetting its own). Or perhaps store the keys in a namespace and delete the namespace?

@Paxa offered this as his solution:

```ruby
def logout
  if logged_in?
    @current_user = current_user if @current_user.nil?
    before_logout!(@current_user)
    reset_sorcery_session
    after_logout!
    @current_user = nil
  end
end

def reset_sorcery_session
  reset_session # protect from session fixation attacks
rescue NoMethodError
end
```
When we call logout - then all session data will be removed.

In my case I fix so:
```
def reset_sorcery_session
  session.delete(:user_id)
  session.delete(:return_to_url)
  session.delete(:last_action_time)
  session.delete(:login_time)
end
```

Of course Devise would also need to be modified to not reset the session on logout either :)

**Comment by Ch4s3** [comment]
I'm not sure this is a use case we can officially support unfortunately.

**Comment by brendon** [comment]
No worries. :)
