### ISSUE TITLE
Updated wiki for incompatibilities

### ISSUE THREAD

**Issue by FunkyloverOne** [Sorcery/sorcery#113]
Guys, I've just updated your wiki, I didn't know that GitHub will allow me to do so without any permissions / forks. So just in case, I'm leaving here this issue to let you know that I have updated your wiki, here are my changes:
https://github.com/Sorcery/sorcery/wiki/Known-incompatibilities/_compare/601226c7fcb14a9bf2d4628c13e5d2630b3492a1...30436a47406a87d18bf65581dd808f75f867b4fb

**Comment by FunkyloverOne** [comment]
Also, I think that 'sorcery' gem must go after 'rails' gem, as ActiveRecord is inside 'rails'.
So this `if` block will be triggered:
https://github.com/Sorcery/sorcery/blob/master/lib/sorcery.rb#L69

As for mongoid - it should be added before sorcery, so the following `if` block will trigger :)
https://github.com/Sorcery/sorcery/blob/master/lib/sorcery.rb#L82

**Comment by Ch4s3** [comment]
@FunkyloverOne Thanks!
