### ISSUE TITLE
require_login_from_http_basic getting looped on Chrome

### ISSUE THREAD

**Issue by FunkyloverOne** [Sorcery/sorcery#115]
It works perfectly first time, but if you will log out and immediately (without closing your browser) will try to log in again - it will get looped, and it will be asking for login and password, it will not log in until you visit any other page (changing url manually), and then try to log in again, that time everrything will be OK again.

I know why it is happening (kind of), but I do not know how to fix it. Here's the line causing this problem:
https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/controller/submodules/http_basic_auth.rb#L39

Now explanation:

**1st time** everything is as expected:
- `request.authorization.nil? || session[:http_authentication_used].nil?` - both are `true`,
- so this code is running:
```ruby
request_http_basic_authentication(realm_name_by_controller) && (session[:http_authentication_used] = true) && return
```
- and now when login dialog appears `session[:http_authentication_used]` is not nil anymore,
- and when user provides credentials 
- `request.authorization.nil? || session[:http_authentication_used].nil?` - both are `false`
- and then actual authentication logic, e.g. `require_login` works, everything is OK.

Then, after logout, **2nd time** login is broken:
- `request.authorization.nil? || session[:http_authentication_used].nil?` - `false || true`,
- and this code is kinda running, but something is wrong:
```ruby
request_http_basic_authentication(realm_name_by_controller) && (session[:http_authentication_used] = true) && return
```
- for some reason `request.authorization.nil? || session[:http_authentication_used].nil?` does not change at all, it's still same `false || true`, no matter how much times you're trying to type in credentials
- and **only** if you will visit any other page and than try to log in again
`request.authorization.nil? || session[:http_authentication_used].nil?` - `true || false`
- and when user provides credentials everything is working

So, it seems like when `request.authorization` is present, then session doesn't seem to be reloading... I do not really getting it.

**UPDATE**

This behavior was observed on Incognito Window, on regular window this behavior is even worse.
After logging out, credentials prompting is looped, BUT after visiting other page & trying to log in again - it actually logs you in as previous (logged out) user.

**UPDATE 2**

Everything is totally fine on Firefox, I had such issues only on Chrome.

**Comment by FunkyloverOne** [comment]
BTW, what is `realm` for `request_http_basic_authentication`? I wasn't able to find anything about it.

**Comment by athix** [comment]
Closing this out as there hasn't been any movement.

@FunkyloverOne if you still need help, please comment/reopen!
