### ISSUE TITLE
undefined login_at Rails 5.2 --api

### ISSUE THREAD

**Issue by mecurc** [Sorcery/sorcery#120]
```NoMethodError (undefined method `login_at' for #<OauthsController:0x00007f4ea8256770>)```

**Comment by shiroemons** [comment]
```
auth_at_provider_path(:provider => :xxxxx)
```

**Comment by athix** [comment]
@dmitry-vakhnenko, did @shiroemons' suggestion solve your issue?

**Comment by Ch4s3** [comment]
ping @dmitry-vakhnenko

**Comment by athix** [comment]
Still no response, closing this out...
