### ISSUE TITLE
How to do reactivate when user changes email address?

### ISSUE THREAD

**Issue by kysnm** [Sorcery/sorcery#123]
Is there a documentation or wiki pages?
Please teach me how to do it.

**Comment by zentooo** [comment]
In app/models/user.rb:

```
before_update :setup_activation, if: -> { email_changed? }
after_update :send_activation_needed_email!, if: -> { previous_changes["email"].present? }
```

It works for me.

**Comment by athix** [comment]
If someone has the time to add this to the wiki, I would appreciate it. I likely won't have a chance to update the docs until after `1.0.0`.

**Comment by mladenilic** [comment]
@athix: Moved the @zentooo's comment to the [User Activation](https://github.com/Sorcery/sorcery/wiki/User-Activation) wiki page.

Cheers! ;)

**Comment by athix** [comment]
Thanks @mladenilic! :)

Closing this out.
