### ISSUE TITLE
undefined method `sorcery_adapter' for nil:NilClass

### ISSUE THREAD

**Issue by garmoshka-mo** [Sorcery/sorcery#127]
```
undefined method `sorcery_adapter' for nil:NilClass

sorcery (0.12.0) lib/sorcery/model/submodules/external.rb:42:in `load_from_provider'
sorcery (0.12.0) lib/sorcery/controller/submodules/external.rb:121:in `login_from'
app/controllers/oauth_controller.rb:12:in `callback'
```

When attempting to:

```
 if @user = login_from(provider)
```

Implemented from official example

**Comment by mladenilic** [comment]
@garmoshka-mo: If you take a look at `lib/sorcery/model/submodules/external.rb:42`, you'll see that `sorcery_adapter` method is being called on `config.authentications_class` – in your case, this is null.

Here's the line I'm talking about: https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/model/submodules/external.rb#L42

You should add the following to the sorcery initializer:
```
user.authentications_class = Authentication
```

P.S. keep in mind that the authentications class could be different if you did not follow the wiki guild – https://github.com/Sorcery/sorcery/wiki/External

Best,
Mladen

**Comment by athix** [comment]
Closing this out as there hasn't been any movement, @garmoshka-mo please comment/reopen if you still need any help.
