### ISSUE TITLE
find_by_credentials doesn't use indexes on user table

### ISSUE THREAD

**Issue by tdtadeu** [Sorcery/sorcery#131]
Checking the newrelic of an app I'm working on, I found that User.find times on session create are incredibly high, so I manually ran all the stack and this is what I found:
```
irb(main):019:0> condition = User.arel_table["email"].lower.eq(User.arel_table.lower("test_email"))
irb(main):020:0> User.where(condition).explain
=> EXPLAIN for: SELECT "users".* FROM "users" WHERE LOWER("users"."email") = LOWER('test_email') /*application*/
                          QUERY PLAN
--------------------------------------------------------------
 Seq Scan on users  (cost=0.00..40269.10 rows=4668 width=465)
   Filter: (lower((email)::text) = 'test_email'::text)
(2 rows)
```
If this query was using an index, it would say as much in the explanation, like so:
```
irb(main):027:0> User.where(email: "test_email").explain
=> EXPLAIN for: SELECT "users".* FROM "users" WHERE "users"."email" = $1 /*application*/ [["email", "test_email"]]
                                     QUERY PLAN
------------------------------------------------------------------------------------
 Index Scan using index_users_on_email on users  (cost=0.42..8.44 rows=1 width=465)
   Index Cond: ((email)::text = 'test_email'::text)
(2 rows)
```

Is this an expected behaviour? Or maybe I got something messed up on my app?

I'm using sorcery 0.12.0 and rails 4.2.5.1 on ruby 2.2.4

**Comment by Ch4s3** [comment]
Interesting. We do add an index on Email, as you can see [here](https://github.com/Sorcery/sorcery/blob/80affcf2a892d9fe4213bca403b6fe197f67a234/lib/generators/sorcery/templates/migration/core.rb#L11). I don't have access to a project running soprcery at the moment, can you check this @athix? @tdtadeu can you confirm that you have that index?

**Comment by Ch4s3** [comment]
This could be related to #119 which should be fixed. Let me know when you have a moment to check @tdtadeu.

**Comment by athix** [comment]
Theoretically this should be resolved now. Closing, but please comment/reopen if this issue shows up again.
