### ISSUE TITLE
Loads ActionController::Base in Rails applications always

### ISSUE THREAD

**Issue by andrewhood125** [Sorcery/sorcery#132]
Rails has an `--api` option that changes the default parent of the ApplicationController from ActionController::Base to ActionController::API. 

That class has some good documentation on why you would not want to load the entire ActionController::Base class.

https://github.com/rails/rails/blob/94360451eae2701fc04d6b132c44d9622bbe0cb5/actionpack/lib/action_controller/api.rb#L8-L11

In the engine: https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/engine.rb#L11-L13

ActionController::Base is explicitly referenced. In a rails app that has been configured this is the first time that file will have been referenced and it will now be loaded. During load it also initializes a number of modules including RequestForgeryProtection.

**Comment by athix** [comment]
I believe this has been fixed by the on_load calls.
