### ISSUE TITLE
Race condition in activation mail.

### ISSUE THREAD

**Issue by lostpupil** [Sorcery/sorcery#134]
There might be a race condition when the user sign up.
In sidekiq, there is a "could not found User with id=1".
Also I read the souce code, but I did not see there is something like delay in the config file.

**Comment by athix** [comment]
The activation email should be an after_create callback (see [user_activation.rb](https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/model/submodules/user_activation.rb#L48)), so it shouldn't be getting scheduled until after Rails has written to the database. I would double check to ensure there isn't something preventing the data from getting written to the DB.

**Comment by Ch4s3** [comment]
@lostpupil can you post some code?

**Comment by lostpupil** [comment]
```
# in my sorcery.rb
user.user_activation_mailer = UserMailer
user.email_delivery_method = :deliver_later
```
@athix Actually, I think it should not be `after_create`, it should be `after_commit` instead.
I checked my code, I think there is nothing wrong to prevent it saving the record to the database, the record will be there immediately. But the delay job mailer will be failed anyway.
@Ch4s3 I am just follow the basic example post in wiki, but I use that config file in staging env. FIrst time it will raise an `Record not found` exception, then this job will be executed after 1 minute.

```
# user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  audited

  include AASM
  include Filterable
  mount_uploader :avatar, AvatarUploader

  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] || reset_password_token_changed? }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password]}
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password]}

  validates :email, presence: true, uniqueness: true, 'valid_email_2/email': true
  validates :avatar, file_size: { less_than: 1.megabytes }

end
```

**Comment by Ch4s3** [comment]
@lostpupil interesting. Can you throw an after_commit and after after_create on your model that log something out, to see if it is succeeding or failing on the first run?

**Comment by lostpupil** [comment]
@Ch4s3 Thanks,  My colleague and I came up with the same idea, that version worked.
But I am also wondering is there any chance to add a delay method to the email sending code.

```ruby
      def generic_send_email(method, mailer)
        config = sorcery_config
        mail = config.send(mailer).send(config.send(method), self)
        if defined?(ActionMailer) && config.send(mailer).is_a?(Class) && config.send(mailer) < ActionMailer::Base
          mail.send(config.email_delivery_method)
        end
      end
```

**Comment by Ch4s3** [comment]
@lostpupil if you submit a PR, I'll take a look. I'll also try to cut a release soon.
