### ISSUE TITLE
`method_missing': undefined method `sorcery' upgrading to rails 5.2 --api only

### ISSUE THREAD

**Issue by chriscarpenter12** [Sorcery/sorcery#138]
I had a rails 5.1 api app that I tried upgrading to 5.2 and whenever I try to boot up the server it complains about the initializer in `config/initializers/sorcery.rb`. 

```
1: from /Users/chris/Sites/dashboard-api/config/initializers/sorcery.rb:5:in `<main>'
/Users/chris/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `sorcery' for #<Rails::Application::Configuration:0x00007fb457a967e0> (NoMethodError)
```

Relevant lines in `config/initializers/sorcery.rb`:
```ruby
# The first thing you need to configure is which modules you need in your app.
# The default is nothing which will include only core features (password encryption, login/logout).
# Available submodules are: :user_activation, :http_basic_auth, :remember_me,
# :reset_password, :session_timeout, :brute_force_protection, :activity_logging, :external
Rails.application.config.sorcery.submodules = []

# Here you can configure each submodule's features.
Rails.application.config.sorcery.configure do |config|
```

Nothing crazy in my initializer. Its failing at the first line of code. Its like my sorcery gem isn't loading. Where can I look why? Has no issue if I stash my changes and continue with 5.1

**Comment by athix** [comment]
Can you try the latest master? [#129](https://github.com/Sorcery/sorcery/pull/129) mentions fixing issues related to `Rails 5.2`.

**Comment by athix** [comment]
Closing this out, please comment/reopen if this is still an issue!
