### ISSUE TITLE
BruteForceProtection#lock! conflicts with ActiveRecord#lock!

### ISSUE THREAD

**Issue by eford1** [Sorcery/sorcery#14]
This means I can't use `lock!` or `with_lock!` on any object that calls `authenticates_with_sorcery!`.

http://api.rubyonrails.org/classes/ActiveRecord/Locking/Pessimistic.html

**Comment by athix** [comment]
Looks like the lock! functionality is new to Rails 5. We'll probably just want namespace or rename the BruteForce lock so it doesn't conflict.

**Comment by eford1** [comment]
Thanks for fixing!
