### ISSUE TITLE
You have incorrectly defined user_class or have forgotten to define it in intitializer file (config.user_class = 'User')

### ISSUE THREAD

**Issue by sarnold04** [Sorcery/sorcery#144]
After the sorcery installation in my Rails 5.2.1 (Ruby 2.5.0) I get the mentioned error: You have incorrectly defined user_class or have forgotten to define it in intitializer file (config.user_class = 'User')

User model was created and created to work with Mongoid (7.0.1).

Anyone know what can cause these error?

**Comment by PatrickMcSweeny** [comment]
Did you set the value in initializer file?
