### ISSUE TITLE
External submodule add_provider_to_user method not working when authentications_class belongs to a module definition

### ISSUE THREAD

**Issue by hugogilmar** [Sorcery/sorcery#146]
When you define `user.authentications_class` and the class is behind a Module an `undefined method` error raises.

![image](https://user-images.githubusercontent.com/119041/45770575-0124a200-bc00-11e8-9f0d-936455855699.png)

Related to this lines:

https://github.com/Sorcery/sorcery/blob/eea7a1c852a9da8a6729cedacd7c4c292a2897d7/lib/sorcery/model/submodules/external.rb#L48

https://github.com/Sorcery/sorcery/blob/eea7a1c852a9da8a6729cedacd7c4c292a2897d7/lib/sorcery/model/submodules/external.rb#L95

Maybe a `demodulize` call missing.

**Comment by athix** [comment]
Should be resolved by next gem release, please reopen if issue persists!
