### ISSUE TITLE
Which branch should I use for implementation?

### ISSUE THREAD

**Issue by asmsuechan** [Sorcery/sorcery#16]
Hello.

It's just a bit question. I'm not sure the branch operation of this repository. I recognize branch 0-9-x is release branch. But recent commit is on master. Which branch should I use for implementation?

**Comment by athix** [comment]
Hi @asmsuechan, afaik 0-9-x is considered the stable 0.9 release branch, and will only receive hot-fixes going forward. Master is the current development branch and the most up-to-date, however there may be issues present, use with care. Rubygems currently uses the latest on 0-9-x.

**Comment by asmsuechan** [comment]
Thanks for your reply! I'll throw PRs at master branch. I'd like to refactor codes by using rubocop.

**Comment by athix** [comment]
No problem!
