### ISSUE TITLE
User not being placed in the session after Rails 4.2-5.2 upgrade

### ISSUE THREAD

**Issue by brandoncc** [Sorcery/sorcery#169]
### Configuration

- Sorcery Version: `0.13.0`
- Ruby Version: `2.3.5`
- Framework: `Rails 5.2`
- Platform: `Mac`

### Expected Behavior

When I call `#login` in my controller it should place the user id in the session.

### Actual Behavior

When I call `#login` in my controller, it returns the user as it should. It doesn't place the user in the session though so it isn't actually logged in. I have a feeling it is some configuration that should be changed due to my Rails 4.2->5.2 and Sorcery 0.9.1->0.13.0 upgrades which caused this, I just don't know what it is.

### Steps to Reproduce

I'm not sure how to reproduce it in any app other than my specific situation.

**Comment by athix** [comment]
@brandoncc I would check the wiki and make sure your controller code looks up to date. (~3 years since `0.9.1`)

Assuming everything looks good, I would try stepping the versions up in smaller increments, and see if you can narrow down which version breaks your application. That would give a better idea of where to look.

**Comment by athix** [comment]
I don't see any commits that look like they would break compatibility. Weird that it only breaks after `0.11.0`.. I know there's a file that rails generates when migrating to version 5, I would recommend looking at that and see if anything looks like a potential cause. Beyond that, I'll need some more information to help more.

**Comment by brandoncc** [comment]
Thanks for the help @athix, I will probably stick with 0.10.3 for now so I can at least get things running right on Rails 5, then I can revisit this.

**Comment by athix** [comment]
No problem, good luck!

**Comment by brandoncc** [comment]
@athix I went back to my properly functioning Rails 4.2 app and replicated this. When I upgrade to 0.10.3, all is well. When I go to 0.11.0, the user does not persist in the session again. What can I share with you that will help you help me debug? Thanks again.

**Comment by athix** [comment]
@brandoncc let's start off with making sure the params are being passed properly. Can you use `byebug` or a similar tool, and check `params` before the `login` method gets called? Also, just to be sure it's not a separate issue, please also check `session[:user_id]` before and after `login` gets called. We'll want to do this for `0.10.3` and `0.11.0` to see if there's any differences.

Also don't forget to sanitize any sensitive data if posting the stack trace.

**Comment by brandoncc** [comment]
0.10.3:

```
[1] pry(#<SessionsController>)> params
=> {"utf8"=>"✓",
 "authenticity_token"=>"pw1R4yWN2oJ6ea8SCz8f0ZlSE5nMDcDGCy3FIWHmCm2dDsq7Kxs9WbjgMOXbB+Ivg6QzUiw==",
 "email"=>"brandoncc@gmail.com",
 "password"=>"password",
 "commit"=>"Sign in",
 "controller"=>"sessions",
 "action"=>"create"}
```
0.11.0:

```
[1] pry(#<SessionsController>)> params
=> {"utf8"=>"✓",
 "authenticity_token"=>"5zyFKYgxOPTDfrj115Av7oaaLWYTSJOv69RRikS0Je8HKAAoKgVWR9pKlBhia2P/U7YO22VFgptQ==",
 "email"=>"brandoncc@gmail.com",
 "password"=>"password",
 "commit"=>"Sign in",
 "controller"=>"sessions",
 "action"=>"create"}
```

0.11.0 before `#login` call:

```
[3] pry(#<SessionsController>)> session["user_id"]
=> nil
```

0.11.0 after `#login` call:

```
[1] pry(#<SessionsController>)> session["user_id"]
=> nil
```

I found something interesting... I did `bundle open sorcery` and I placed a pry as the first line inside of `user_class.authenticate`. It doesn't get called! If it helps you debug, my user class is `Account`

**Comment by athix** [comment]
@brandoncc interesting. Does your `Account` class call `authenticates_with_sorcery!`?

Also, try replacing your config with [the latest version](https://github.com/Sorcery/sorcery/blob/master/lib/generators/sorcery/templates/initializer.rb). The following lines might be what's giving you trouble:

* 277 - `# user.subclasses_inherit_config =`
* 530 - `config.user_class = '<%= model_class_name %>'`

**Comment by athix** [comment]
Damn, it was worth a shot.

Can you try checking `0.10.3` to make sure it's setting `session[:user_id]`?  It's important to test both the same way, as testing just one doesn't tell us if there was a change between versions. (I think rails does differentiate between a symbol and string when used as an index) What I'm expecting to see is `0.10.3` has the ID after login, but `0.11.0` does not.

Also, can you use pry inside the login method, immediately before the `user_class.authenticate` block? We'll want to inspect `user_class` to make sure it's present, and that it responds to the `authenticate` method. If you never hit that pry either, then it might be that a controller is overwriting the `login` method.

**Comment by brandoncc** [comment]
I just verified that `session[:user_id]` gets set in 0.10.3. I then did the same test in 0.11.0 again and it was `nil` as usual.

`user_class` returns `Account`, and `user_class.authenticate` returns `nil` if I pass it invalid info and the correct user if I pass it valid credentials. The block still doesn't get called :-/

**Comment by athix** [comment]
@brandoncc That's...peculiar. If the method is defined properly and returning as expected, I don't see any reason it shouldn't be executing the block. Are you sure your pry is the first line in the block? (between [L37-38](https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/controller.rb#L37))

While we're at it, place a `pry` call inside the [model method](https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/model.rb#L86). It shouldn't get hit either, but it would be telling if it does.

**Comment by brandoncc** [comment]
Okay....I figured it out. I have an `Account.authenticate` method. The question is, why does 0.10.3 work?! I think I followed a tutorial 5 years ago when I built the app which showed how to encrypt the user's email and password in the db data which is why the `authenticate` method is needed. I think I am actually going to remove the encryption anyway so I will be able to upgrade after that. Thank you so much for helping me figure this out! By the way, When the model method didn't get called I ran `show-source Account.authenticate` in pry and lo and behold...I had my override method.

Thanks again!

**Comment by athix** [comment]
> I think I am actually going to remove the encryption anyway so I will be able to upgrade after that.

Good chance you already know, but you should never save a password in the database in a retrievable format. Current best practice is to use something like bcrypt and a randomized salt to hash the password for later comparisons.

>Thank you so much for helping me figure this out!

Glad to help! 😄

**Comment by brandoncc** [comment]
Thanks for making sure I knew that, as it seems there are lots of people who don't think about things like that! When I built the app I went the extra 100 miles and actually encrypted the db column data using attr_encrypted (some other columns too like email). So bcrypt is in place and than attr_encrypted on top of that.....safest app on the web! :-D

**Comment by brandoncc** [comment]
Just to close this out, I removed the `.authenticate` method and my extra encryption stuff and the upgrade went smooth. I'm sorry for wasting your time :-/

**Comment by athix** [comment]
I got to learn more about the codebase and to look for method overwriting as a potential cause for issues. Don't worry about it! If you ever want to help out with the project, currently the documentation could use some loving.

**Comment by brandoncc** [comment]
Noted! I'll see if I can spare some time to work on it. Are there any particular areas of the docs that should be addressed sooner than others?
