### ISSUE TITLE
Incorrect table name in migrations when model is namespaced

### ISSUE THREAD

**Issue by palkan** [Sorcery/sorcery#174]
### Configuration

- Sorcery Version: `0.13.0`
- Ruby Version: `2.5.3`
- Framework: `Rails 6.0.0.beta1`

### Expected Behavior

Running `rails g sorcery:install --model "MyModule::User"` I expect the migrations to use `my_module_users` table name.

### Actual Behavior

Instead I have `my_module/users` table name in the migrations.

**Comment by athix** [comment]
I wonder if this is a bug with the `tableize` method, which is what we use in the migration generator:

https://github.com/Sorcery/sorcery/blob/master/lib/generators/sorcery/templates/migration/core.rb#L3

If anyone would like to tackle fixing this bug, that would be a good place to start looking.

**Comment by crimson-knight** [comment]
It's not a bug, tableize doesn't handle namespaces like the desired outcome. I forked the repo and I'll put up a pull request with a new helper method I made that accounts for the name spaces and adjusts the table name accordingly. I've also updated the generators to use the new helper method.

**Comment by kentarohorie** [comment]
> It's not a bug, tableize doesn't handle namespaces like the desired outcome. I forked the repo and I'll put up a pull request with a new helper method I made that accounts for the name spaces and adjusts the table name accordingly. I've also updated the generators to use the new helper method.

https://github.com/Sorcery/sorcery/pull/237

**Comment by athix** [comment]
Between these two PRs, I think the issue has been resolved:
* https://github.com/Sorcery/sorcery/pull/237
* https://github.com/Sorcery/sorcery/pull/274

If something is still broken with the table names, let me know and I can reopen this.
