### ISSUE TITLE
Support for Rails 5.2 CurrentAttributes?

### ISSUE THREAD

**Issue by Spone** [Sorcery/sorcery#177]
This is a suggestion to replace `current_user` with Rails 5.2 new feature [`CurrentAttributes`](https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html).

The main advantage is being able to access `Current.user` from within a model, without having to pass the `current_user` from the controller action.

Would you be interested in supporting this in Sorcery?

**Comment by athix** [comment]
As long as backwards compatibility is kept, I would be fine with this change.

**Comment by athix** [comment]
If anyone would like to take this on, please feel free! Closing this for now as no additional commentary is needed.
