### ISSUE TITLE
External module redirects page without actually logging in the user (Google OAuth)

### ISSUE THREAD

**Issue by risafj** [Sorcery/sorcery#192]
### Configuration

- Sorcery Version: `0.14.0`
- Ruby Version: `2.6.2`
- Framework: `Rails 5.2.3`
- Platform: `Heroku`

### Expected Behavior

I'm trying to implement an OAuth system for Google accounts. I don't need a standalone login system for my app, so I just use the `external` submodule.
I've followed the official [tutorial](https://github.com/NoamB/sorcery/wiki/External) closely with minor modifications for outdated parts (like skipping the use of `attr_accessible`). This is how I'd like it to go:
1. User clicks the "Login with Google" link
2. User selects their Google account
3. User gets logged in, then redirected to the root page

### Actual Behavior

Steps 1 and 2 go fine, but then the user is redirected to the root page without being logged in. The Heroku logs look like this:

```
Processing by OauthsController#callback as HTML
Parameters: {"provider"=>"google", "code"=>"[some long string]", "scope"=>"email profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"}
Authentication Load (1.6ms)  SELECT  "authentications".* FROM "authentications" WHERE "authentications"."uid" = $1 AND "authentications"."provider" = $2 ORDER BY "authentications"."id" ASC LIMIT $3  [["uid", "[some long string]"], ["provider", "google"], ["LIMIT", 1]]
Redirected to https://[myapp].herokuapp.com/
Completed 302 Found in 163ms (ActiveRecord: 1.6ms)
```

Is there something wrong with my configuration or the callback method?

```ruby
# oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_action :require_login

  def oauth
    login_at(auth_params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)

        reset_session
        auto_login(@user)
        redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
      rescue StandardError
        redirect_to root_path, alert: "Failed to login from #{provider.titleize}!"
      end
    end
  end

  private

  def auth_params
    params.permit(:code, :provider)
  end
end
```

```ruby
# sorcery.rb (everything except below has been left as default)

# Google-related config
config.google.key = ENV['SORCERY_GOOGLE_CLIENT_ID']
config.google.secret = ENV['SORCERY_GOOGLE_CLIENT_SECRET']
config.google.callback_url = ENV['SORCERY_GOOGLE_CALLBACK_URL']
config.google.user_info_mapping = { email: 'email', username: 'name' }
config.google.scope = 'https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile'

# Class for authentication
user.authentications_class = Authentication
```
### Steps to Reproduce
I've created an isolated repo with just this OAuth system:
https://github.com/risafj/goo_oauth
Really appreciate if you could clone it and/or examine the code.

**Comment by athix** [comment]
@risafj can you try updating your callback method to the following and hitting it again?

```ruby
  def callback
    byebug
    provider = params[:provider]
    if @user = login_from(provider)
      byebug
      redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
    else
      begin
        byebug
        @user = create_from(provider)

        reset_session
        auto_login(@user)
        byebug
        redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
      rescue StandardError
        byebug
        redirect_to root_path, alert: "Failed to login from #{provider.titleize}!"
      end
    end
  end
```

**Comment by risafj** [comment]
Thank you for the quick response.
First of all, I realised that I'd been using strong params named `auth_params`, but had kept my code referring to `params`, so I fixed that (also updated the code snippet above).
However, that didn't seem to be related at all, as the results below show.

```
[22, 31] in goo_oauth/app/controllers/oauths_controller.rb
   22:   #   end
   23:   # end
   24: 
   25:   def callback
   26:     byebug
=> 27:     provider = auth_params[:provider]
   28:     if @user = login_from(provider)
   29:       byebug
   30:       redirect_to root_path, notice: "Logged in from #{provider.titleize}!"
   31:     else
```

```
(byebug) provider
nil

(byebug) auth_params
Unpermitted parameter: :scope
<ActionController::Parameters {"code"=>"[long string]", "provider"=>"google"} permitted: true>

(byebug) auth_params[:provider]
Unpermitted parameter: :scope
"google"
```

Not sure why `auth_params[:provider]` is returning `"google"` and yet it's not being assigned to the `provider` variable. Please let me know if there's anything I should inspect/try out. Thank you so much!

**Comment by risafj** [comment]
Ok, I thought it was strange that the local variable `provider` was returning `nil`, so I tried it without assigning the provider to a variable as written below, and suddenly it works...

```ruby
def callback
    if @user = login_from(auth_params[:provider])
      redirect_to root_path, notice: "Logged in from #{auth_params[:provider].titleize}!"
    else
      begin
        @user = create_from(auth_params[:provider])

        reset_session
        auto_login(@user)
        redirect_to root_path, notice: "Logged in from #{auth_params[:provider].titleize}!"
      rescue StandardError
        redirect_to root_path, alert: "Failed to login from #{auth_params[:provider].titleize}!"
      end
    end
  end
```
I've never seen this behaviour, and I honestly have no idea why. But using `byebug` did help pinpoint the issue, so thank you for that.

**Comment by risafj** [comment]
Thank you for your suggestion to fiddle around with `byebug`. I ultimately found that the `user_info_mapping` line in the config file seems to have been the problem. I changed it to this:

```ruby
config.google.user_info_mapping = { email: 'email' }
```

And now it works. Thank you!

**Comment by athix** [comment]
Glad to help! Closing this for now, please reopen if you run into any other issues.

**Comment by athix** [comment]
Re: the provider variable being `nil`, there's a good chance that's because the first byebug was before the variable was declared. I would try adding it again now that the mapping is fixed.

**Comment by risafj** [comment]
Thank you again. By the way, are the `user_info_mapping` items fixed for each external provider? For example, is there any way to get not only the `email` but also the user's first and last names from Google? I can't seem to find anything on the docs about it.

**Comment by risafj** [comment]
And yes, the `byebug` issue was simply because the variable hadn't been defined yet. It was a silly mistake so I deleted the comment afterwards 😅

**Comment by athix** [comment]
You should be able to map everything that gets passed by the oauth provider. Documentation is pretty scarce, but if you use byebug you can inspect the hash that gets sent back and figure out the names from there. The main problem is making sure the scope has the fields you're looking for.

It might be a bit tricky inspecting the hash response, iirc you have to call a specific method so it sets the instance variable with the hash. If you have trouble figuring it out, let me know and I'll dig it up.

**Comment by athix** [comment]
No worries, I've made plenty of similar mistakes. All a part of the learning process. 😄

**Comment by risafj** [comment]
I am finding it to be tricky, if you could point me in a direction I'd really appreciate it.

What I've tried so far: I put `byebug` in the very beginning of the `callback` method and tried inspecting the `response` json, but it was so convoluted that I couldn't find any related info except this (which is not helpful either):

```
(byebug) response.request.params
{"provider"=>"google", "code"=>"[long string]", "scope"=>"email profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile", "controller"=>"oauths", "action"=>"callback"}
```

In the same `byebug`, I also tried calling some of the methods in the `external` submodule like [sorcery_fetch_user_hash](https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/controller/submodules/external.rb#L79), but these got rejected.

```
*** OAuth2::Error Exception: invalid_grant: Bad Request
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

**Comment by risafj** [comment]
Also checked out Google's OAuth docs, but I couldn't find anything beyond [this](https://developers.google.com/identity/protocols/googlescopes):

__Google OAuth2 API, v2__
__Scopes__
https://www.googleapis.com/auth/userinfo.email | View your email address
https://www.googleapis.com/auth/userinfo.profile | See your personal info, including any personal info you've made publicly available

So you're right, there's the question of whether the scope has the fields I'm looking for (first and last name).

**Comment by risafj** [comment]
>By the way, are the user_info_mapping items fixed for each external provider? For example, is there any way to get not only the email but also the user's first and last names from Google?

For anyone who stumbles across this and wonder if there's a solution, I figured out how:
1. Use `byebug` here:

```ruby
# oauths_controller.rb
def callback
    provider = auth_params[:provider]
    byebug
    if @user = login_from(provider)
    # continues
```

2. Inside `byebug`, do this:
  * `sorcery_fetch_user_hash(:google)`: Should return nil
  * `@user_hash`:
Should return a long hash with that looks like this:
`{:token=>"<long string>", :refresh_token=>nil, :expires_at=> <integer>, :expires_in=> <integer>, :user_info=>{"id"=>"<numbers>", "email"=>"email@email.com", "verified_email"=>true, "name"=>"<full name>", "given_name"=>"<first name>", "family_name"=>"<last name>", "picture"=>"<jpg url>", "locale"=>"ja", "hd"=>"<domain>"}, :uid=>"<numbers>"}`

I'm guessing that if you use other items, such as `given_name` or `family_name` in your `user_info_mapping`, you can get those in addition to the default two (`email` and `name`). I haven't tried this myself because our project decided to go another direction.
