### ISSUE TITLE
User_info_mapping for getting Google profile info in OAuth callback?

### ISSUE THREAD

**Issue by risafj** [Sorcery/sorcery#193]
### Configuration
- Sorcery Version: `0.14.0`
- Ruby Version: `2.6.2`
- Framework: `Rails 5.2.3`
- Platform: `Heroku`

### Expected Behavior
I'm trying to implement an OAuth system for Google accounts. I don't need a standalone login system for my app, so I just use the `external` submodule.
I can sign up/sign in the user correctly if I only map the `email` info from Google's response, but not if I try to map anything else. I would also like to get the user's first/last names from the `profile` scope if possible.

Could you advise me on how to do this, or provide some pointers on what to do if I want to parse Google's json response for additional `user_info_mapping`? I tried using `byebug` but couldn't figure it out.

### Actual Behavior
In #192, I asked about my Google OAuth config. Ultimately, changing the `user_info_mapping` worked, even though it meant I was only getting the email address in the response.

```ruby
# sorcery.rb
# Changed from this:
config.google.user_info_mapping = { email: 'email', username: 'name' }

# To this:
config.google.user_info_mapping = { email: 'email' }
```

However, later I remembered that I'd taken the original config with `username: 'name'`directly from the official `initializer` [example](https://github.com/Sorcery/sorcery/blob/master/lib/generators/sorcery/templates/initializer.rb#L156). So it seems like the officially recommended setup isn't working?

### Steps to Reproduce
I've created an isolated repo with just this OAuth system:
https://github.com/risafj/goo_oauth

Thank you so much in advance!

**Comment by risafj** [comment]
I later realised the issue: my `users` table did not have a `username` column. Now that I've added this column, my app signs in/signs up users and saves both `email` and `username` correctly.

Though this may just be me, I feel like it's kinder to first-timers  if there was a line in the official [tutorial](https://github.com/NoamB/sorcery/wiki/External) or [initializer example](https://github.com/Sorcery/sorcery/blob/master/lib/generators/sorcery/templates/initializer.rb#L156) saying any `user_info_mapping` items need to be a column in the `user` table. Closing this issue anyhow.

**Comment by athix** [comment]
@risafj Yeah, the documentation honestly could use a lot of loving. I don't think it's really been modified in a couple years. If you want to, any help with updating the wiki would be greatly appreciated! Even if it's just taking what you learned and generalizing it for reuse, I'm sure others would appreciate it as well. Any PRs that update the auto-generated documentation are also appreciated.

**Comment by risafj** [comment]
@athix Good point. I updated the part about `user_info_mapping` 😃 

> The `user_info_mapping` takes care of converting the user info from the provider (Twitter/Facebook) into the attributes of the User. For example, the "screen_name" that we receive from Twitter will be mapped to the User's `username`.
>This means that there needs to be a column in your User table for each attribute being mapped. If your User table doesn't have the necessary columns, make sure to generate them in your migrations or your login system won't work.

**Comment by athix** [comment]
Awesome, thanks @risafj! 😄
