### ISSUE TITLE
Don't redirect to JSON after sign in

### ISSUE THREAD

**Issue by kevin-smartpatients** [Sorcery/sorcery#195]
I'm using sorcery to authenticate a Rails+React app with JSON requests through Axios. 

- sorcery (0.14.0)
- rails (5.2.3)
- axios@^0.19.0

My sign in form is rendered by rails.  I have this in SessionController

````
  def create
    if login @credentials.email, @credentials.password
      redirect_back_or_to(:home)
    else
      render action: 'new'
    end
  end
````

This works great if the return_url points to an html page but if the last request was for JSON, you get redirected to a JSON response.

I think this line (sorcery/controller.rb:28) is the culprit:

````
session[:return_to_url] = request.url if Config.save_return_to_url && request.get? && !request.xhr?
````

`request.xhr?` looks for the http header `HTTP_X_REQUESTED_WITH` which is not set by Axios.

This page describes the problem:
https://makandracards.com/makandra/48944-xhr-is-not-json
  
I can workaround this by changing my client-side code to add the `HTTP_X_REQUESTED_WITH` header but I wonder if it wouldn't be better to only save the `return_to` address for html requests?

_Obligatory compliment: After years of fighting with Devise & Authlogic, I wish I had discovered Sorcery years ago_

**Comment by athix** [comment]
So the issue I see, is that the solution in that article relies on `responds_to` to correctly interpret the type of request, which (I think) we can't do in the method where `session[:return_to_url]` is set. Unfortunately, I don't think you can rely on that in the create method either, as `session[:return_to_url]` is being overwritten regardless of the final `session#create` request. The best solution probably is setting that header so that the Sorcery method knows to ignore the JSON requests.

Unfortunately I'm still learning about JSON requests, sorry I can't be of more help here. 😞

**Comment by kevin-smartpatients** [comment]
You can get the mime-type of the request with `request.format`.

So I'm suggesting that we change this:

    session[:return_to_url] = request.url if […snip…] && request.get? && !request.xhr?

to this

    session[:return_to_url] = request.url if […snip…] && request.get? && request.format.html?

I can't think of a reason to redirect to another format but, if that's too drastic, we could prevent the most common case (redirects to JSON) with this

    session[:return_to_url] = request.url if […snip…] && request.get? && !request.format.json?

**Comment by athix** [comment]
>You can get the mime-type of the request with `request.format`.

Ah, nice!

To reduce the amount of breaking change, I think the best compromise is probably:

```ruby
session[:return_to_url] = request.url if […] && request.get? && !request.xhr? && !request.format.json?
```

Unless the only use-case for xhr is json, I think this would be safer compatibility-wise.

**Comment by kevin-smartpatients** [comment]
I agree.

**Comment by athix** [comment]
@kevin-smartpatients can you open a PR with the change, and I'll approve/merge it?

**Comment by kevin-smartpatients** [comment]
Will do.

**Comment by kevin-smartpatients** [comment]
Done: https://github.com/Sorcery/sorcery/pull/197

I kept the !request.xhr? and added !request.format.json? so that non-JSON xhr requests will still be blocked form :return_to.

**Comment by athix** [comment]
Merged into master, should be available in the next release or immediately if you point bundler at the github repo.
