### ISSUE TITLE
Rails 6 app with reader/writer database.yml unable to update activity logging

### ISSUE THREAD

**Issue by sqlninja** [Sorcery/sorcery#198]
### Configuration

- Sorcery Version: `0.12.0`
- Ruby Version: `2.6.3`
- Framework: `Rails 6.0.0.rc1`
- Platform: `macOS & Heroku`

### Expected Behavior
All insert / update / delete cmds to be sent to writer
Or add an option in Sorcery config to set database connection to writer
Or allow overriding of activity module database (and probably other modules)

### Actual Behavior
Appears that updates are being sent to follower (readonly)

### Steps to Reproduce

- Create rails 6 app
- setup database yml to have replicas
- set application record to use `connects_to`
- Install sorcery
- install submodules (specifically activity logging)

**Comment by sqlninja** [comment]
Example `database.yml`
```default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: my_app_dev
  follower:
    <<: *default
    replica: true
    database: my_app_dev

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *default
    database: my_app_test
  follower:
    <<: *default
    replica: true
    database: my_app_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  follower:
    <<: *default
    replica: true
    url: <%= ENV['FOLLOWER_DATABASE_URL'] %>
```

Example `ApplicationRecord` rb file
```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :primary, reading: :follower }
end
```

**Comment by sqlninja** [comment]
Bumping in hopes of some advice...

**Comment by athix** [comment]
Hi @sqlninja. Unfortunately I'm not very familiar with how Sorcery handles the ORM adapters, so I don't know how much I can help you directly here.

What I would recommend doing is trying to narrow down where Sorcery is going wrong with the ORM, and see if you can update it to ignore the follower databases. One method you could use to narrow down the source is creating a fork of sorcery, and pointing your development environment at the fork. Then in the fork, try using a debugger like `byebug` in the various parts of the stack to narrow down where the checks are needed, and try adding them.

Sorry that I can't be of more help here, if you need any additional guidance on what files to look at our how to try debugging the issue please let me know.

**Comment by athix** [comment]
Closing this as there hasn't been any movement in a while, please comment/reopen if there's still questions here!
