### ISSUE TITLE
Update rubygems.org

### ISSUE THREAD

**Issue by athix** [Sorcery/sorcery#2]
Currently [rubygems.org](https://rubygems.org/gems/sorcery) refers to `NoamB/sorcery`. This should be updated to `Sorcery/sorcery` once everything is in order.

**Comment by Ch4s3** [comment]
Yeah, I've talked to @arnvald about this. I think we can do that for version 1+.

**Comment by athix** [comment]
Looks like this got updated at some point along the way, closing.
