### ISSUE TITLE
Rails 5 Release

### ISSUE THREAD

**Issue by athix** [Sorcery/sorcery#20]
Creating this issue to discuss releasing a version that fixes all the rails 5 deprecation warnings. Probably won't have time to develop some of the more major items, so I was thinking maybe call this release 0.10.0 and have it be the last release before we go through the existing code with a fine tooth comb and modularize the various features (1.0.0). IIRC, master branch solves most if not all of the problems, so it will be more going through and verifying it's production ready.

@Ch4s3, what are your thoughts and availability? I'll likely be able to dedicate large amounts of time over the next week or two to getting this done.

**Comment by athix** [comment]
Running into this issue when trying to use the latest version in my app, any ideas?

<img width="508" alt="screen shot 2016-12-22 at 2 45 30 pm" src="https://cloud.githubusercontent.com/assets/1802598/21443002/8a0a477c-c856-11e6-8b94-04511b3149f1.png">

**Comment by kyuden** [comment]
@athix  Did you try to do `bundle update`?

**Comment by dankimio** [comment]
Should we weaken dependency requirements?

**Comment by athix** [comment]
@kyuden This error is from running `bundle update`.

I've looked into this a bit more, and it's looking like oauth2's outdated dependencies are the cause of the issue. There's open pull requests to fix them (`intridea/oauth2` [#277](https://github.com/intridea/oauth2/pull/277),[#278](https://github.com/intridea/oauth2/pull/278)), but until that happens I don't really know what we can do to fix it.

**Comment by athix** [comment]
Resolved the issue by locking the twitter gem to `~> 5.0`.
