### ISSUE TITLE
Support for returning refresh tokens in the external module (OAuth)?

### ISSUE THREAD

**Issue by risafj** [Sorcery/sorcery#201]
Hi, do you have any plans to return not only the [`access_token`](https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/controller/submodules/external.rb#L92) but also the [`refresh_token`](https://developers.google.com/identity/protocols/OAuth2WebServer#offline) when logging the user in via the external module? The `refresh_token` allows the `access_token` to be refreshed when it expires in one hour.

Right now, the `@user_hash` being returned looks like this (I'm using Google as the provider), and the `refresh_token` is nil.

`{:token=>"<long string>", :refresh_token=>nil, :expires_at=> <integer>, :expires_in=> <integer>, :user_info=>{"id"=>"<numbers>", "email"=>"email@email.com", "verified_email"=>true, "name"=>"<full name>", "given_name"=>"<first name>", "family_name"=>"<last name>", "picture"=>"<jpg url>", "locale"=>"ja", "hd"=>"<domain>"}, :uid=>"<numbers>"}`

**Comment by athix** [comment]
If anyone would like to extend the return hash to include refresh token, I would certainly take a look at the PR and merge it in if everything looks fine. That being said, ideally we will be refactoring sorcery to depend on Omniauth for the external module, and I'm sure Omniauth already has this functionality implemented for most if not all providers.

**Comment by risafj** [comment]
Hi @mtomov,

Thank you for the response and the code snippet!
Ultimately, the issue our team found was that Sorcery's request to Google didn't state that the request was for offline access. Google doesn't provide a refresh token unless you specify as such ([source](https://developers.google.com/identity/protocols/OAuth2WebServer#offline)), and that's why our refresh tokens were coming back empty.
```ruby
@auth_url = '/o/oauth2/auth'
```
https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/providers/google.rb#L18

 So we overrode the `auth_url` like this in `config/initializerssorcery.rb`.
```ruby
config.google.auth_url = '/o/oauth2/auth?access_type=offline'
```

Then, we could access the refresh token like this in the controller (because as you say, "the refresh_token is actually part of the access_token"): `@access_token.refresh_token`.

I raised this Github issue before learning that overriding the auth_url was an option. So now, this is a non-issue for me, though I still think it may be kinder to users if offline access was enabled by default.
Please feel free to close this issue if necessary.

**Comment by athix** [comment]
I think it would make sense to add this to the wiki, and add a note in the initializer for the Google oauth config.

I assume that offline access would require additional permissions from the end user, so changing the default behavior would be a breaking change for applications that don't utilize the refresh token.

**Comment by risafj** [comment]
@athix That's a good point. Let me check again if the `auth_url` is the only item that needs to be overridden for refresh tokens to become available, and then I'll update the external module wiki.

**Comment by athix** [comment]
Sounds good, thanks @risafj!

**Comment by mtomov** [comment]
@risafj In my brief tests, with the default configuration (no change in `auth_url`), I still am getting the refresh token. It might be something on google's end with the way oauth is set-up or something. Not sure.

**Comment by risafj** [comment]
@mtomov Hmm... I wonder what the difference between our configurations are.
I have this small app with the minimal Sorcery setup necessary to use the external module, and`@user_hash.refresh_token` and `@access_token.refresh_token` still both come back as nil.

```
(byebug) @user_hash
{:token=>"ya29.Il-vB50lIA0eo-...", :refresh_token=>nil, ...}
(byebug) @access_token
#<OAuth2::AccessToken:0x00007f81f94b2878 @token="ya29.Il-vB50lIA0eo-..., @refresh_token=nil, @expires_in=3600, @expires_at=1572689334, ...}
```

I just overrode the `auth_url` and now the responses come back with a refresh token.

This is the repo - please check it out if you have a chance: https://github.com/risafj/goo_oauth

**Comment by mtomov** [comment]
Maybe it's related to this?

https://github.com/oauth-xx/oauth2/issues/321

**Comment by mtomov** [comment]
Actually I figured it out. In my first try, I followed the API demo on the google api pages where there was a one-button-click way to create oauth credentials. Those turned out to be of type "other", which doesn't require setting redirect urls, and a few other settings, it doesn't persist for the user, and seems like it gives a `refresh_token` by default.

![image](https://user-images.githubusercontent.com/1651750/68090839-9a4c6180-fe70-11e9-91b0-80b36c836c64.png)

I now went to create a new Oauth flow, and chose the web application type

![image](https://user-images.githubusercontent.com/1651750/68090852-c667e280-fe70-11e9-84db-d174c167b514.png)

and, yes, I don't have a refresh token with the default settings : )

---
Adding `config.google.auth_url = '/o/oauth2/auth?access_type=offline'` absolutely works! Thanks a lot @risafj ! I'm happy to submit a PR as suggested with a comment on this setting. 

Btw, also be careful not to loose the refresh token - [as you only even get one](https://developers.google.com/identity/protocols/OpenIDConnect#refresh-tokens)  per authorization. People were puzzled on that - see here https://github.com/googleapis/google-api-python-client/issues/213#issuecomment-360288626

**Comment by risafj** [comment]
Awesome, thank you @mtomov  :)
Oh, just realised I'd missed @athix 's suggestion about raising a PR with a comment. I just updated the wiki, I'll raise a PR with a comment too, later.

**Comment by mladenilic** [comment]
@athix, @risafj Can this issue be closed as well?

**Comment by athix** [comment]
@mladenilic I think so, yes. There's plenty of information here for anyone looking to solve this in the future, and SEO typically does a good job of finding these issues.

For anyone finding this: if this doesn't cover your specific scenario, please feel free to open a new issue with additional details.
