### ISSUE TITLE
Additional Maintainer(s) Needed

### ISSUE THREAD

**Issue by athix** [Sorcery/sorcery#204]
Unfortunately, with both of the current maintainers (@Ch4s3 and myself) occupied with work and other projects, the Sorcery 1.0 update has slowed to a standstill.

If there's anyone in the community that would like to become a maintainer, or otherwise help with the project on a consistent basis, please reach out to me either via this issue or the email listed on my profile.

Even if you can't commit to helping consistently or are less experienced, any assistance with updating the wiki, reviewing PRs, etc is greatly appreciated! Even small things like updating templates to match the new rails syntax would be helpful.

**Comment by Ch4s3** [comment]
I'd be happy to help onboard someone in a couple of weeks.

**Comment by z1lk** [comment]
I would like to help. Can you point me to some good first issues, a roadmap to 1.0, etc? Whatever needs to be done really. I would love to get my hands dirty.

**Comment by Ch4s3** [comment]
@z1lk we don't really have a roadmap, but it would involve breaking out many of the integrations into separate repos and getting up to speed with Rails 6.

You may want to look into some issues involving Rails 5.2 and 6 support.

**Comment by athix** [comment]
@z1lk if you're still interested in helping, I've been marking various PRs and Issues as help wanted. Any assistance with those would be greatly appreciated!

This invitation extends to the entire ruby community as well! Even if you're relatively new to ruby, or aren't familiar with working on open source projects, I would be more than willing to help guide you on how to get started. Please either reach out on this issue, or email me directly if you do want some help getting started.

Thanks!

**Comment by amialive** [comment]
I'd be more than happy to help. Please, can you provide me with some guidance? I'll really appreciate it :)

**Comment by athix** [comment]
@amialive Certainly! Depending on your level of familiarity, there's quite a few different types of things that can be tackled, ranging from giving the wiki/documentation some TLC to helping implement major functionality like JWT support. If you tell me what would be the most comfortable for you, I can find a good issue for you to start with, and help guide you through the process.

**Comment by amialive** [comment]
Absolutely! I'm experienced in Ruby, familiar with Sorcery (just as user, haven't dived into the internals) and fairly new to OSS. So open to collaborate in any task you consider :)

**Comment by athix** [comment]
Sounds good! How about this: can you look at the open issues/PRs marked "Help Wanted" and then ping me on one that catches your eye?

**Comment by amialive** [comment]
How about [this one](https://github.com/Sorcery/sorcery/pull/218)? So that I can start getting familiar with the code, help documenting and unblock a feature request?

**Comment by crimson-knight** [comment]
I'm working on some of my own gem ideas, and since I used Sorcery as a reference for how the rails engines/plugins work, I'll give back and push some updates for you guys 😁

**Comment by athix** [comment]
Much appreciated! 😄

**Comment by WhiteOcean737** [comment]
Hi! I would like to get involved!

**Comment by athix** [comment]
@WhiteOcean737 yup! If you get stuck or have questions just let me know.

**Comment by athix** [comment]
I recently saw some other open-source projects using the "Easy" label for identifying good tasks to start with. I think I'll give this a shot and see if it helps ease people into contributing. It can be a bit intimidating if the first "Help Wanted" you look at is something like the JWT integration.

**Comment by ebihara99999** [comment]
@athix 
I will restart contributing Sorcery again!  At first, I'm going to watch the opening issues and PRs.

**Comment by kentarohorie** [comment]
Sorcery is my favorite gem. I also would like to help! I'm going to watch issues and PRs  which have 'Help Wanted' label.

**Comment by athix** [comment]
I've decided to commit 10-20 hours a week to working on Sorcery going forward, which should hopefully solve this issue. For the longer term, I'll be looking into Github Sponsorship and other donation methods to provide a method to support Sorcery's development without needing to work directly on it. Having that in place should hopefully prevent us from getting into this scenario again in the future.

That being said, I still welcome anyone and everyone to participate if you're interested! Getting started on open source can be intimidating, so if you want to help but don't know how feel free to reach out either via Github issue or by contacting me directly (see README.md).
