### ISSUE TITLE
Want to fix your wiki?

### ISSUE THREAD

**Issue by yuina1056** [Sorcery/sorcery#206]
Sorry for not good at English .

https://github.com/Sorcery/sorcery/wiki/Testing-Rails#functional-tests

Should be written in rails_helper, not spec_helper.
I was in trouble because I could not use testhelper.

I'll edit it if I don't have enough hands, what do you do?

**Comment by athix** [comment]
Oh, that is weird. It looks like we have part of the page written for MiniTest, and the rest for RSpec. That could definitely be cleaned up a bit, perhaps with a separate section for MiniTest and RSpec.

If you want to help update it, any assistance is greatly appreciated. If you want, I can also take a look and fix any grammar issues afterwards.

**Comment by athix** [comment]
I'm closing this issue as there's no active questions or comments, but if anyone stumbles upon it later, help with the wiki is still needed and appreciated!
