### ISSUE TITLE
Inaccurate Naming Convention for crypted_password and Encryption in General In the Library

### ISSUE THREAD

**Issue by jonmchan** [Sorcery/sorcery#207]
I know this most likely won't be able to be fixed since the project is so well-established, but the naming convention of "encrypting" the password is technical wrong. Passwords are not encrypted, but just hashed. This has security implications on whether you can recover the original password without bruteforce techniques. As far as I know, your default implementation of using bcrypt is secure and only produces a hash, but the entire naming structure ([crypted_password](https://github.com/Sorcery/sorcery/blob/ae02d2e07431daf287f055293790486ac073be6f/lib/sorcery/model/config.rb#L59),  [encrypt](https://github.com/Sorcery/sorcery/blob/ae02d2e07431daf287f055293790486ac073be6f/lib/sorcery/model.rb#L125), etc.) is a technical misnomer.

**Comment by mladenilic** [comment]
I think "crypted" here just means "not plain". Devise actually uses "encrypted_password". 

But I agree with you, it is misleading – something like `password_hash` would be more accurate. I wouldn't mind having this change on 1.0 roadmap.

**Comment by athix** [comment]
Once this has been added to our roadmap, this issue can be closed out. We can do that as a part of the discussion for #104.

**Comment by athix** [comment]
This is still an issue, and ideally will be solved at some point in the future (or Sorcery will become obsolete, whichever comes first. 😛 ).

Closing this for now however, we should have enough cross references to find this if someone takes up the mantle of getting Sorcery 1.0 rolling.
