### ISSUE TITLE
TravisCI Builds Failing

### ISSUE THREAD

**Issue by athix** [Sorcery/sorcery#213]
It appears the configuration for the test database creation needs to be updated for TravisCI. All builds are failing due to the following error:

```
$ mysql -e 'create database sorcery_test;'

ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

The command "mysql -e 'create database sorcery_test;'" failed and exited with 1 during .
```

**Comment by mladenilic** [comment]
Can we just remove the command from the `travis.yml`? Based on spec app, sqlite is used – https://github.com/Sorcery/sorcery/blob/master/spec/rails_app/config/database.yml

**Comment by athix** [comment]
Interesting, that might be specific to the app within the specs but it's worth a shot regardless.

**Comment by athix** [comment]
So that resolves the database error, and now it's just stuck on sprockets expecting a manifest file. I think there might be a PR or Issue floating around for that (sprockets 4 breaking things).

**Comment by mladenilic** [comment]
I already replied on the PR ;)

https://github.com/Sorcery/sorcery/pull/214#issuecomment-559213228

**Comment by athix** [comment]
Perfect! Thanks @mladenilic and @Plsr!
