### ISSUE TITLE
Cannot use login method in sorcery because of changes to rails

### ISSUE THREAD

**Issue by Uzay-G** [Sorcery/sorcery#220]
The wiki for [Testing with Rails](https://github.com/Sorcery/sorcery/wiki/Testing-Rails) provides this following example:
```ruby
class TeamsControllerTest < ActionController::TestCase
  include Sorcery::TestHelpers::Rails::Integration
  include Sorcery::TestHelpers::Rails::Controller

  setup do
    @team = teams(:one)
    @user = users(:one)

    login_user(user = @user, route = login_url)  # replace with your login url path
  end

  test "should get index" do
    get :index
    assert_response :success
    assert_not_nil assigns(:teams)
  end
```

Unfortunately, the `ActionController::TestCase` that the test inherits from is now [deprecated](https://blog.bigbinary.com/2016/04/19/changes-to-test-controllers-in-rails-5.html) and no longer works. But, if we change this deprecated class to what is now used for controllers, `ActionDispatch::IntegrationTest`, we get the following error:
`Undefined method 'auto_login' for nil:NilClass`.

So, as of Rails 5, I think it's impossible to use the controller test methods.

How can we fix this?

**Comment by athix** [comment]
@mladenilic do you want to try tackling getting the test helpers refactored for the latest rails version(s)?

**Comment by mladenilic** [comment]
@athix sure, you can assign this one to me.

**Comment by Uzay-G** [comment]
Is there a way we can bypass this until there is a fix? Thanks a bunch!

**Comment by mladenilic** [comment]
Hi @Uzay-G, `ActionDispatch::IntegrationTest` does not expose controller instance the way `ActionController::TestCase` did. You'll have to create an actual login request first, before running the test. You can find more info here https://github.com/rails/rails/issues/23386#issuecomment-192954569 until we update test helpers and documentation.

**Comment by Uzay-G** [comment]
Oh alright thanks.
I managed to get it work and will post the solution here if anyone is having the same problem.
In `users_controller_test.rb`:
```ruby
def test_login_as(user, password)
  post "/user_sessions", params: { username: user.username, password: password }
end

class UsersControllerTest < ActionDispatch::IntegrationTest

  setup do
    @user = users(:one)
    test_login_as(@user, "secret")
  end
end
```
The function posts to the "/user_sessions" url to login. A key thing to note with this approach is the `password` parameter. The password corresponds to what you used to generate a crypted password for your fixtures user. For example, my `users(:one)` looks like this:
```ruby
one: 
  email: dev@olio.com
  salt: <%= salt = "asdasdastr4325234324sdfds" %>
  username: Devo
  crypted_password: <%= Sorcery::CryptoProviders::BCrypt.encrypt("secret", salt) %>
  activation_state: active
```
As you can see, sorcery encrypts the string "secret" and stores the encrypted version. When we login, it will encrypt the `password` parameter and compare it to the `crypted_password`. So, in this case, if I login with `users(:one)`. I will run `test_login_as(users(:one), "secret"`.
I hope this helps! :+1:

**Comment by Uzay-G** [comment]
Nice to see this got trick got added to the wiki! Maybe we could change the login_user method to take into account these changes in modern rails apps? Or should I just close this issue?

**Comment by athix** [comment]
@Uzay-G I think we can close this out. A lot of Sorcery needs to be refactored, and as a part of that most of the code should be updated to the latest standards (Rails 6, Ruby 2.7 at time of writing).

**Comment by Uzay-G** [comment]
Alright. The method I said is in the docs so it's no problem :)
