### ISSUE TITLE
Extend activation_token_expiration_period when send authentication email again to user before the user is successfully authenticated

### ISSUE THREAD

**Issue by f-teruhisa** [Sorcery/sorcery#221]
`activation_token_expiration_period` is determined at the first time of user authentication, that is, by [`setup_activation`](https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/model/submodules/user_activation.rb#L90) (if it is defined in initializer).

There is no problem for normal operation.
However, user may have passed due date to check the authentication email.

If the activation_token_expiration_period is not extended when sending the recertification email(from Rails system), some developers have to extend it using Rails console.

I'm thinking of implementing a method in user_activation.rb to update activation_token_expiration_period, but I want to know how developers think about this.

### Configuration

- Sorcery Version: `0.14.0`
- Ruby Version: `2.6.1`
- Framework: `Rails 5.2.3`
- Platform: `macOS`

### Expected Behavior
Activation_token_expiration_period can automatically be update and  extended.

### Actual Behavior
Activation_token_expiration_period is not automatically updated.

### Steps to Reproduce
Passed due date to check the authentication email, and then attempt to reauthenticate.

**Comment by mladenilic** [comment]
Hi @f-teruhisa, 

If a token is expired, you probably do not want to just extend the expiration date but generate a new token instead. 

You can do this by calling `setup_activation` on the user model instance, right?

**Comment by f-teruhisa** [comment]
Hi @mladenilic .
Thank you for comments.

That is exactly what you say.
In other words, when I send authentication email again, should execute `setup_activation`.
