### ISSUE TITLE
Changes in Github API affect the use of External Oauth login

### ISSUE THREAD

**Issue by Uzay-G** [Sorcery/sorcery#223]
Hey, I just got an email about this: https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/.

Sorcery has a **great** module you can add for oauth login. This is documented here: https://github.com/Sorcery/sorcery/wiki/External. Now I was using the github oauth with that module, where u have to provide your `client_id` and `app_secret` and then sorcery handles the rest.

So I know that behind the hood Sorcery is making the request with the query parameters because I got a warning about it because they are becoming deprecated and I just wanted to warn you so that you could maybe take into account this change of the Github API and modify the code so this will work.

The changes are pretty small, instead of putting the parameters inside the query, they need to be inside the headers.

Would this be possible or not?

I would love to help with this although I don't know the codebase and I'd like to thank you for the amazing tool you built!

**Comment by athix** [comment]
Hi @Uzay-G, thanks for the heads up on Github updating it's API!

If you want to try tackling this, a good place to start would be the provider file: [lib/sorcery/providers/github.rb](https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/providers/github.rb)

Let me know if you do want to try taking this on and need any help. Having more people is always welcome! :)

**Comment by Uzay-G** [comment]
Is that all the code for the github provider? It's not a lot. I will try to see what I can figure out :+1:

**Comment by Uzay-G** [comment]
Hey! it turns out I was wrong and Sorcery isn't the problem with this. It got pinged because of another Github app I have that was making the wrong call. I'll still be happy to contrib to this awesome lib!

How can I get started?

**Comment by athix** [comment]
@Uzay-G there should be a few issues/PRs listed as help wanted, help those in particular would be highly appreciated. Otherwise, there's always some help that could be done with getting the documentation up-to-date with the latest Rails standards (I think a lot of them were written for Rails 4, and used outdated hash style, etc).

Let me know if you have any questions! 😄
