### ISSUE TITLE
How can use only credentials.yml.enc without secrets.yml?

### ISSUE THREAD

**Issue by leadbrain** [Sorcery/sorcery#225]
Recently I setting up new rails project without secrets.yml.
But session is not working normally.
It looks like only working with secrets.yml for secret_key_base
Is there another solution for this?

### Configuration

- Sorcery Version: `0.14`
- Ruby Version: `2.7.0`
- Framework: `rails 6.0.2`
- Platform: `linux`

### Expected Behavior

Using `secret_key_base` on credentials.yml.enc

### Actual Behavior

Only working with secrets.yml for `secret_key_base` instead of credentials.yml.enc

### Steps to Reproduce

Deploy rails app on two or more server without secrets.yml

**Comment by crimson-knight** [comment]
@leadbrain Did you deploy and make sure that your master.key file is available on all of your servers? It sounds like your app just isn't able to decrypt the credentials.yml.enc file.

**Comment by athix** [comment]
@leadbrain is this still an issue?
