### ISSUE TITLE
What about a v0.9.2 ?

### ISSUE THREAD

**Issue by guizmaii** [Sorcery/sorcery#24]
Hi,

Is there any plan to push a v0.9.2 ?
The changelog between v0.9.1 and the master branch is already big: https://github.com/Sorcery/sorcery/compare/v0.9.1...master.

Jules

**Comment by athix** [comment]
Probably not, because of the rails 3 and rails 5 changes it will more likely be `0.10.0`.

**Comment by Ch4s3** [comment]
@athix mentioned, we already have a number of breaking changes on master, we probably need to get it together and do a major-ish release. I've dropped the ball a bit.
