### ISSUE TITLE
Ruby 2.7.1 deprecation warnings

### ISSUE THREAD

**Issue by kapso** [Sorcery/sorcery#240]
Seeing these warnings after upgrading to Ruby 2.7.1

### Configuration

- Sorcery Version: `0.15.0`
- Ruby Version: `2.7.1`
- Framework: `Rails 6.0.3`

Warning:
```
/app/vendor/bundle/ruby/2.7.0/gems/sorcery-0.15.0/lib/sorcery/adapters/active_record_adapter.rb:38: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/app/vendor/bundle/ruby/2.7.0/gems/activemodel-6.0.3/lib/active_model/callbacks.rb:144: warning: The called method is defined here
```

**Comment by athix** [comment]
[active_record_adapter.rb#L38](https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/adapters/active_record_adapter.rb#L38)

[Potentially related blog post](https://piechowski.io/post/last-arg-keyword-deprecated-ruby-2-7/)

rails/rails#38202

**Comment by athix** [comment]
Sounds like the solution is changing L38 to the following?

```ruby
@klass.send "#{time}_#{event}", method_name, **options.slice(:if, :on)
```

**Comment by athix** [comment]
This should be resolved on current master.
