### ISSUE TITLE
A different version of login method for API only applications?

### ISSUE THREAD

**Issue by jasdeepsingh** [Sorcery/sorcery#242]
Is there a variation of the `login` method that can be called to login users in an API only application? 

For instance, my application is API only, I require all the before/after hooks to be run that sorcery runs here: https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/controller.rb#L37..L64

However, running the `form_authenticity_token` method makes no sense in an API only application.

I could use the `UserClass.authenticate` method, however this method does not run a lot of the hooks that sorcery relies on for most other submodules to work, brute force protection for instance.

To make matters worse, My login logic is contained inside of a PORO/Service class where the controller context is absent forcing me to pass down the controller context down into my PORO/Service class which rigidly ties my PORO/Service class to be aware of the controller context.

### Configuration

- Sorcery Version: `0.15.0`
- Ruby Version: `2.6.0`
- Framework: `Rails`

**Comment by kapso** [comment]
Yea ran into the same issue when using `ActionController::API`

**Comment by jasdeepsingh** [comment]
For now, this is what I ended up doing:

```ruby
class PORO

  class_eval do
    Sorcery::Controller::Config.submodules.each do |mod|
      begin
        include Sorcery::Controller::Submodules.const_get(mod.to_s.split('_').map(&:capitalize).join)
      rescue NameError
      end
    end
  end

  def call
    # REDACTED 

    credentials = [email, password]
    User.authenticate(*credentials) do |user, failure_reason|
      if failure_reason
        after_failed_login!(credentials)
          
        # custom error handling CODE REDACTED
      end

      # setup user session here CODE REDACTED

      after_login!(user, credentials)
    end
  end

end

private

def after_login!(user, credentials = [])
  Sorcery::Controller::Config.after_login.each { |c| send(c, user, credentials) }
end

def after_failed_login!(credentials)
  Sorcery::Controller::Config.after_failed_login.each { |c| send(c, credentials) }
end

def user_class
  @user_class ||= Sorcery::Controller::Config.user_class.to_s.constantize
rescue NameError
  raise ArgumentError, 'You have incorrectly defined user_class or have forgotten to define it in intitializer file (config.user_class = \'User\').'
end
```

**Comment by athix** [comment]
Unfortunately API support so far has been...sparse to put it kindly. I think a lot of the API support will probably be a part of the JWT integration, although that area is honestly a bit outside my current base of understanding.

I would very much welcome any PRs that help Sorcery with API support, especially considering the general move towards using rails as a REST API and javascript frameworks for rendering. Realistically speaking, for this to get done someone from the ruby community will have to step up and help with the implementation. That person might end up being me, but it won't be for a while if that's the case.

**Comment by jasdeepsingh** [comment]
@athix that's not a problem, I was able to unblock myself for now. I'll see if I can get to implementing JWT support for Sorcery in the coming couple of weeks.

Thanks for your attention on this!
