### ISSUE TITLE
magic_login by email

### ISSUE THREAD

**Issue by josegrad** [Sorcery/sorcery#243]
Sorcery Version: 0.14.0
Ruby Version: 2.4.5
Framework: Rails 4.2.8
Using Mongoid

Is the magic_login feature ready?

Is it hidden from the readme file.
Shouldn´t rails generate sorcery:install session_timeout activity_logging magic_login generate the User model with the required fields?

**Comment by athix** [comment]
@josegrad I would say that it's less hidden, and more incomplete. If you'd like to help flesh out the README and `sorcery:install` command to better support the submodule, I'm sure others would appreciate it as well. It's not a feature that I use personally, so I haven't looked into the submodule much myself.

**Comment by josegrad** [comment]
We used our own solution for the project we have now. But we´ll probably take a look next time at see how to do it with Sorcery.
