### ISSUE TITLE
Is it OK to add a wechat provider?

### ISSUE THREAD

**Issue by Darmody** [Sorcery/sorcery#25]
Wechat, a chinese chat app. http://open.weixin.qq.com

I think many chinese developer would like to have this provider.

If you like this idea, i can create a PR for it.

**Comment by dankimio** [comment]
It's OK as long as it follows the format of other providers.

**Comment by Darmody** [comment]
@dankimio Cool!

**Comment by athix** [comment]
We'll be changing how providers work for `1.0.0` (integrating omniauth and/or refactoring into new module) but in the meantime there should be no issues with adding new providers. Don't forget to add the provider to the changelog for your PR! :)
