### ISSUE TITLE
Question: how to specify nested attributes in `user.username_attribute_names` ?

### ISSUE THREAD

**Issue by vlad0337187** [Sorcery/sorcery#254]
Please complete all sections.

### Configuration

- Sorcery Version: `0.14.0`
- Ruby Version: `2.7.1`
- Framework: `Rails 6.0.2 + Mongoid 7.1.0`
- Platform: `Fedora 32`

### Expected Behavior

when I specify attributes with point:
`user.username_attribute_names = ['authdata.username', 'authdata::email']`
sorcery` should access nested attributes on `User` model

### Actual Behavior

It just creates user model with attributes with points:
`<User _id: 5f2c971ee13823dd2cf7b03e, created_at: nil, updated_at: nil, authdata.username: nil, authdata::email: nil, email: nil, crypted_password: nil, salt: nil, remember_me_token: nil, remember_me_token_expires_at: nil, reset_password_token: nil, reset_password_token_expires_at: nil, reset_password_email_sent_at: nil, activation_state: nil, activation_token: nil, activation_token_expires_at: nil, name: nil>`

### Steps to Reproduce
Specify 
`user.username_attribute_names = ['authdata.username', 'authdata::email']`,

create user model with nested model - authdata:

<details>

<summary>code</summary>

<pre>
=begin
Re-generate view files for updated model:
    bundler exec rails  generate slim:scaffold  User  username:string email:string password:string  --force
(just change fields)
=end

class User
    include Mongoid::Document
    include Mongoid::Timestamps

    authenticates_with_sorcery!
    embeds_one :authdata, autobuild: true, class_name: 'UserAuthData'
    accepts_nested_attributes_for :authdata

    field :name, type: String
end

class UserAuthData
    include Mongoid::Document

    embedded_in :user

    field :username, type: String
    field :email,    type: String
    field :password, type: String

    # indexes created only on document insert
    # to avoid this -
    index({username: 1}, {unique: true})
    index({email: 1},    {unique: true})
end

</pre>

</details>

than just create new user:
`user = User.new`

and see that `sorcery` added attributes directly to `user`, not `user.authdata`

**Comment by athix** [comment]
Hi @vlad0337187, to clarify it sounds like you're wanting to use nested attributes for username and email, but Sorcery gets confused? I see you have `authdata.username`, but also `authdata::email` and I'm curious why one uses `.` and the other `::`. Is that intentional?

**Comment by vlad0337187** [comment]
@athix , Hello.

Yes, I'd like to use nested attributes for username and email (and sorcery gets confused).

I just specified '::' to see: what will happen.
(I also placed '#' there)
(came from Python, so I'm not fluent with Ruby yet)

**Comment by athix** [comment]
@vlad0337187 Welcome to Ruby! I hope you'll enjoy it, I was pretty happy with how intuitive a lot of it can be. :smile: 

Typically `::` is used for namespacing, for instance `Sorcery::Config` would tell Ruby to first look for a module or class called `Sorcery`, and then a module/class nested inside of that named `Config`. For nested attributes, I think it's normally implemented as methods, which use `.`, e.g. class methods: `User.some_class_method` and instance methods: `user = User.new` `some_hash = { username: user.username, email: user.email }`. I could be wrong on that though, I've used nested attributes pretty sparingly personally.

Unfortunately, it looks like Sorcery doesn't support nested attributes at the moment. Under the hood it looks like it's doing its look-ups directly on the table of your User model, see: [ActiveRecordAdapter#find_by_credentials](https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/adapters/active_record_adapter.rb#L60) I'm not familiar with your use-case, so I'm afraid I can't offer any good alternatives without knowing more.

**Comment by athix** [comment]
Looks like you're also using MongoID which I'm not entirely sure works at the moment. There's no tests for it, and I don't use it personally. Here's the equivalent method for the MongoID adapter: https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/adapters/mongoid_adapter.rb#L54

**Comment by vlad0337187** [comment]
@athix , thank you very much.

Thought to patch `Sorcery` for it to support nested attributes, but not sure: is it a good solution.
Probably, it can be noted in readme, that nested attributes aren't supported for MongoID adapter and close this issue for now.

A see a nice solution - use `has_one` relation of MongoID for such case.
So it won't embed document, which would result to inconvenience with graphical DB exploring and a little bit - with speed, but as for me - it's anyway nicer than having all attributes in one place.

**Comment by athix** [comment]
Closing for now, please reopen if anything else comes up!
