### ISSUE TITLE
User Activation & Reset Password Errors

### ISSUE THREAD

**Issue by zoegod911** [Sorcery/sorcery#258]
Please complete all sections.

### Configuration

- Sorcery Version: `0.15.0`
- Ruby Version: `2.7.0`
- Framework: `Rails`
- Platform: `Web`

### Expected Behavior

I should be able to see User models in `rails c`

### Actual Behavior

`/home/godkingherb/.rvm/gems/ruby-2.7.0/gems/sorcery-0.15.0/lib/sorcery/adapters/active_record_adapter.rb:38: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/godkingherb/.rvm/gems/ruby-2.7.0/gems/activemodel-6.0.3.3/lib/active_model/callbacks.rb:130: warning: The called method is defined here
/home/godkingherb/.rvm/gems/ruby-2.7.0/gems/sorcery-0.15.0/lib/sorcery/adapters/active_record_adapter.rb:38: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/godkingherb/.rvm/gems/ruby-2.7.0/gems/activemodel-6.0.3.3/lib/active_model/callbacks.rb:144: warning: The called method is defined here
**ArgumentError: To use user_activation submodule, you must define a mailer (config.user_activation_mailer = YourMailerClass).
from /home/godkingherb/.rvm/gems/ruby-2.7.0/gems/sorcery-0.15.0/lib/sorcery/model/submodules/user_activation.rb:77:in `validate_mailer_defined**`

### Steps to Reproduce

1. Install gem with submodules
1. Set user_activation_mailer and reset_password_mailer in sorcery.rb in initializers
1. Create a User

I'm not sure what the issue is. I've defined both:
`    user.reset_password_mailer = UserMailer  `
`    user.user_activation_mailer = UserMailer`

& I see the error given above and no access to viewing my created user in the `rails c`

Also, when I remove both submodules from `Rails.application.config.sorcery.submodules`, they seem to reappear after the initializer.

**Comment by zoegod911** [comment]
Just needed a restart to gem `spring`

**Comment by athix** [comment]
Step 1 of debugging: Is the server running?
Step 2 of debugging: Did you try `spring stop`?

:stuck_out_tongue:
