### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by heyvito** [Sorcery/sorcery#268]
Hi there! Before anything, I'd like to say a big thank you for all contributors working on this Gem. It is simply awesome, in all possible aspects. Thank you so much!

I hate to be _that person_, but I'd like to know whether there are plans on releasing a new version on RubyGems; Especially addressing issues mentioned in #240. I also checked #248 (I appreciated the TL;DR, btw! :D), but it seemed a long-term change, and yet, releasing a new version may make sense(?); please correct me if I misunderstood it.

In the meantime, is it safe to use `master` for development purposes?

Once again, thank you!
Best wishes!

**Comment by athix** [comment]
Yeah, you're right. I was hoping to get the v1 release done, but with COVID my productivity hasn't been the greatest. It makes sense to push out the latest additions as-is. For now, master should be fine for development use. I'll also try to cut a new release here in the next few days. If it's still not out in a week, feel free to ping me on this issue.

**Comment by heyvito** [comment]
Hi @athix! Thank you for replying to my message!
I hope that despite our current scenario, you're safe and well!

Please let me know in case you need a helping hand to ship this release!
Thank you so much for your work on this project!

Best wishes!

**Comment by takaho624** [comment]
Hi @athix!
First I'd like to thank you for all your commitment.
While I understand your situation and I also hate to be _that_ person, since the issue is also affecting one of my projects, I'd appreciate it a lot if you could cut a new release on this.
Since you said feel free to ping you, here you go.

Many thanks!

**Comment by athix** [comment]
Sorry for slacking on this, I just released v0.16.0 with the latest changes on master. Please let me know if there are any issues!

**Comment by wout** [comment]
@athix That's great. I'll report back if there are any issues.
