### ISSUE TITLE
user_sessions_path not found when following Simple Password Authentication Tutorial

### ISSUE THREAD

**Issue by mruegenberg** [Sorcery/sorcery#269]
In trying to get started with Sorcery, I followed the [tutorial from the Wiki](https://github.com/Sorcery/sorcery/wiki/Simple-Password-Authentication).

When adding the sessions code, I got the following error:

```
undefined local variable or method `user_sessions_path' for #<ActionView::Base:0x007feaa627ff90>
Did you mean?  users_path
```

Not sure what's going on, as I haven't used Sorcery before, but someone else also seems to have run into this and found some solution:
[https://yasunari-kainuma.com/2020/11/07/sorcery%E5%AE%9F%E8%A3%85%E6%99%82%E3%81%AE%E3%81%A4%E3%81%BE%E3%81%A5%E3%81%8D/]()
[https://translate.google.com/translate?sl=auto&tl=en&u=https://yasunari-kainuma.com/2020/11/07/sorcery%25E5%25AE%259F%25E8%25A3%2585%25E6%2599%2582%25E3%2581%25AE%25E3%2581%25A4%25E3%2581%25BE%25E3%2581%25A5%25E3%2581%258D/]()

**Comment by wout** [comment]
I think there is an error in the tutorail. The problem is this line:

```rb
# app/views/user_sessions/new.html.erb

<%= link_to 'Back', user_sessions_path %>
```

There is no `user_sessions_path` for GET since only `new`, `create` and `destroy are created:

```bash
$ rails g controller UserSessions new create destroy
```

Simply replace `user_sessions_path` to a path that exists, or remove the line altogether.

**Comment by Jaacky** [comment]
I think there was also a problem with the url
user_sessions_path
```rhtml
# app/views/user_sessions/_form.html.erb
<%= form_with url: login_path, method: :post do |f| %>
```
```rhtml
# app/views/user_sessions/_form.html.erb
<%= form_with url: login_path, method: :post do |f| %>
```


https://github.com/Sorcery/sorcery/wiki/Simple-Password-Authentication/4daedcb40913b33c8c075a2aa6e662f2749b016d

**Comment by athix** [comment]
Sounds like the wiki was updated, is everything working now @mruegenberg?

**Comment by athix** [comment]
I'll be revisiting (and modernizing) the documentation for v1 when it's closer to completion.

If anyone is still having issues in the meantime, please comment and I can reopen this.
