### ISSUE TITLE
Unable to install additional modules

### ISSUE THREAD

**Issue by cybercent** [Sorcery/sorcery#275]
Please complete all sections.

### Configuration

- Sorcery Version: `0.15`
- Ruby Version: `2.7`
- Framework: `6.0.3.3`
- Platform: `MacOS`

### Expected Behavior

Able to install additional modules.

### Actual Behavior

Not able to install additional modules.

`undefined method `session_timeout=' for Sorcery::Controller::Config:Module'

### Steps to Reproduce

Install any module.
`rails generate sorcery:install session_timeout --only-submodules`

Update the sorcery config file and chnage one of the attributes, like `session_timeout`

`rake db:migrate`
`undefined method `session_timeout=' for Sorcery::Controller::Config:Module`

Please list all steps to reproduce the issue.

**Comment by cybercent** [comment]
Found the issue, the generator does not add the modules to the array.

**Comment by athix** [comment]
@cybercent could you share what you did differently to get it working? It could be helpful to those who find this issue via SEO in the future.
