### ISSUE TITLE
"merge multiple if condition into one" produces unpythonic formatting 

### ISSUE THREAD

**Issue by Bengt** [Sorcery/sorcery#277]
### Configuration

- Sorcery Version: `latest`
- Platform: `linux`

### Expected Behavior

```python
if (
    tox_environment_name is not None and
    tox_environment_name.startswith('py')
):
```

Note: `and`s mark a line, which will be continued in the next.

### Actual Behavior

```python
if (
    tox_environment_name is not None
    and tox_environment_name.startswith('py')
):
```

Note: The `and`s mark a line, which continues the previous line.

### Steps to Reproduce

Copy and paste this code into PyCharm with Sourcery installed, follow the suggestion.

### Importance

This example is a quite prominent one as the blog mentions it as the very first example:

<https://sourcery.ai/blog/explaining-refactorings-1/>

### Scope

I am not sure whether this is a Sourcery issue or a PyCharm issue.

**Comment by athix** [comment]
Hi @Bengt, I think you meant to post this to the [sourcery-ai/sourcery](https://github.com/sourcery-ai/sourcery) repo. :wink:
