### ISSUE TITLE
Tutorial examples does not work

### ISSUE THREAD

**Issue by trainingstore** [Sorcery/sorcery#279]
Please complete all sections.

### Configuration

- Sorcery Version: `sorcery 0.16.1`
- Ruby Version: `3.0.1p64`
- Framework: `Rails 6.1.3.2`
- Platform: `macOS Big Sur version 11.2.3 (20D91)`

### Expected Behavior
I follow tutorials: Simple Password Authentication (https://github.com/Sorcery/sorcery/wiki/Simple-Password-Authentication) and External (https://github.com/Sorcery/sorcery/wiki/External). I want to make login with Github.
Tell us what should happen.

### Actual Behavior
 It shows Failed to login from github. 

Tell us what happens instead.

### Steps to Reproduce
The code mainally 'copy-paste' from tutorials mentioned above. Something missing in tutorials? Thank you in advance.
Best Regards.
Please list all steps to reproduce the issue.
Follow tutorials mentioned above.

**Comment by athix** [comment]
@trainingstore It's been a while since I've reviewed the tutorials (I'm planning on redoing them once v1 releases).

Can you post the error you're getting? It will help me narrow down which part of the process is broken. Be sure to scrub any sensitive information before posting (e.g. secret keys, IP addresses, etc).

**Comment by trainingstore** [comment]
It doesn't show errors. It shows alert text from OauthsController # callback method: 
rescue
        redirect_to root_path, :alert => "Failed to login from #{provider.titleize}!"

def callback
    provider = params[:provider]
    if @user = login_from(provider)
      redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)
        # NOTE: this is the place to add '@user.activate!' if you are using user_activation submodule

        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, :alert => "Failed to login from #{provider.titleize}!"
      end
    end
  end

**Comment by trainingstore** [comment]
It shows following logs:
Started GET "/oauth/callback?provider=github&code=ad2546b98767ce75f920" for 127.0.0.1 at 2021-05-07 22:09:27 +0300
Processing by OauthsController#callback as HTML
  Parameters: {"provider"=>"github", "code"=>"ad2546b98767ce75f920"}
  Authentication Load (0.2ms)  SELECT "authentications".* FROM "authentications" WHERE "authentications"."uid" = ? AND "authentications"."provider" = ? ORDER BY "authentications"."id" ASC LIMIT ?  [["uid", "58115465"], ["provider", "github"], ["LIMIT", 1]]
  ↳ app/controllers/oauths_controller.rb:12:in `callback'
  TRANSACTION (0.1ms)  begin transaction
  ↳ app/controllers/oauths_controller.rb:16:in `callback'
  User Create (0.6ms)  INSERT INTO "users" ("created_at", "updated_at") VALUES (?, ?)  [["created_at", "2021-05-07 19:09:28.438408"], ["updated_at", "2021-05-07 19:09:28.438408"]]
  ↳ app/controllers/oauths_controller.rb:16:in `callback'
  TRANSACTION (0.1ms)  rollback transaction
  ↳ app/controllers/oauths_controller.rb:16:in `callback'
Redirected to http://0.0.0.0:3000/
Completed 302 Found in 653ms (ActiveRecord: 2.0ms | Allocations: 16293)

**Comment by trainingstore** [comment]
It shows message:
SQLite3::ConstraintException: NOT NULL constraint failed: users.email
I changed 
class SorceryCore < ActiveRecord::Migration[6.1]
  t.string :email,           null: false
to 
t.string :email
did rollback migration. 
It creates user wihtout email. It works.
Thank you very much.

**Comment by athix** [comment]
@trainingstore Sounds like your OAuth scope doesn't contain the user's email, which may or may not matter depending on your application intentions. If it's necessary, I would recommend keeping the `null: false` and adding the appropriate permission scopes to OAuth to request their email on login/signup.

If you run into any other issues, let me know!
