### ISSUE TITLE
Refactoring deletes comments at the end of code file

### ISSUE THREAD

**Issue by komodovaran** [Sorcery/sorcery#280]
### Configuration

- Sorcery Version: `0.9.0`
- Sourcery Plugin Version: `0.9.0`
- Platform: `Windows 10; PyCharm 2021.1.1 (Professional Edition)
Build #PY-211.7142.13

### Expected Behavior

Comments should be left alone.

### Actual Behavior

Comment is deleted when it's placed at the bottom of the file

### Steps to Reproduce

This
```
ls = []
for i in range(10):
    ls.append(i)

# This is a comment below ALL code

# And this

# And this too
```

results in

```
ls = [i for i in range(10)]
```

with all comments below the code deleted.

**Comment by athix** [comment]
@komodovaran wrong project. You probably are looking for [sourcery-ai/sourcery](https://github.com/sourcery-ai/sourcery).
