### ISSUE TITLE
Update user_info of externals after user creation?

### ISSUE THREAD

**Issue by kaikoga** [Sorcery/sorcery#291]
### Configuration

- Sorcery Version: `0.16.1`
- Ruby Version: `2.7.4`
- Framework: `6.1.4.1`
- Platform: `Docker ruby:2.7.4`

### Problems

Sorcery collects user info with the external's `user_info_mapping` just once on user creation, but everything in the external provider actually may change after user creation, e.g. display name, screen_name, bio, or icon of a Twitter account can be changed easily.

That becomes a minor problem if:
- Twitter user @kaikoga (Alice) creates a Sorcery user with Twitter login,
- Screen name of @kaikoga (Alice)'s Twitter changes,
- Somebody else (named Bob) takes screen name @kaikoga on Twitter,
- And we have a Sorcery user (Alice) with screen name @kaikoga not linked to the @kaikoga of Twitter (Bob).

This is headache especially if my app solely targets Twitter users and requires a Twitter login.
Although keeping user_info of every Sorcery user up to date with its external provider is practically impossible, at least I should try.

### Temporary fix

I had to write something like below:

```ruby
class OauthsController < ApplicationController
  # Subset of user_info_mapping, which we want to keep up to date on every login
  USER_INFO_MAPPING_LOGIN = { primary_sns: 'screen_name' }.freeze

  def callback
    if @user = login_from(provider)
      # Keep user data up to date
      @user.update!(user_attrs(USER_INFO_MAPPING_LOGIN, @user_hash))

      redirect_to root_path, :notice => "Logged in from #{provider.titleize}!"
    else
```

Note: this is not perfect because this method requires a user login to update the user_info, and if Bob creates a Sorcery user before Alice login there would be two sorcery users screen-named @kaikoga, which is another problem (This should be separate issue if ever resolved, and currently I'm too lazy to think about it.)

As I was able to workaround and this is pretty much a case by case matter, this may or may not be a library issue.

**Comment by kaikoga** [comment]
Thank you for very quick response! It was too huge a task for me to set up my first cloud environment :dizzy_face: 

In my understanding, for the Bob and Carol cases the user status check must be done within the application. However, in my Real World Case, the Twitter API rate limit is actually too severe to do anything meaningful, so I actually decided to make a compromise and only save Alice, supposed to be the most active user of the three. Thankfully, `user_attrs` and `@user_hash` provided by Sorcery made it very easy to handle the Alice case!

Maybe we could add a setting to update `config.twitter.user_info_mapping` fields at every login (I don't know if existing application break because of this) , but because it is so easy to implement (just two lines of code) I would go ahead and close this issue.

**Comment by athix** [comment]
@kaikoga would you mind sharing your two line solution for people who find this in the future via SEO?

I agree that adding this as a config option to login would make a lot of sense. When I finally have time to get back to Sorcery v1, I'll try to remember that.
