### ISSUE TITLE
crypted_password should be always setup on password validation

### ISSUE THREAD

**Issue by rzepetor** [Sorcery/sorcery#297]
https://github.com/Sorcery/sorcery/blob/032cd2eaf86391e74a3d8a2ab7ae45f42ccaf7c2/lib/sorcery/model.rb#L64-L74

when password is `nil`, `crypted_password` will not change when reset password form is empty, so `change_password` method will be `true` with very common option like this:

```ruby  
validates :password, presence: true, length: { minimum: 7, maximum: 50 }, confirmation: true,
                       if: -> { new_record? or crypted_password_changed? }
```

**Comment by rzepetor** [comment]
Never mind this make more problems than current configuration

**Comment by athix** [comment]
@rzepetor 

It never makes sense to encrypt nil as a password, so the callback is fine as-is.

Typically you'll use client-side validations on any password change forms ([make the input required](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required)), which solves the typical scenario of a user pressing submit before they have entered in the new password.

If you really want, you could also use a virtual attribute and set said attribute to true on any controller actions that involve a password change. This would force those endpoints to validate the password presence, without interfering with other user update calls.

Let me know if you want some code examples, or if this explanation is sufficient.

**Comment by rzepetor** [comment]
Thanks, everything is clear even thought about it earlier but I was looking more clear and simpler solution, so probably I just need add manual validation in controller
