### ISSUE TITLE
Move existing issues

### ISSUE THREAD

**Issue by athix** [Sorcery/sorcery#3]
e.g.
- [#787](https://github.com/NoamB/sorcery/issues/787) - 1.0 Roadmap
- [#779](https://github.com/NoamB/sorcery/issues/779) - rubocop discussion
- [#70](https://github.com/NoamB/sorcery/issues/70) - Token Authentication

And many others..

**Comment by TechRsch** [comment]
I'd like to bump #70.  It's important to API's && microservices, both of which are pretty hot.

**Comment by 5t111111** [comment]
Please consider moving https://github.com/NoamB/sorcery/issues/775 to this current active repository because that issue has not been resolved yet and still seems to have new visitors and comments.

**Comment by athix** [comment]
I think it's time to close this, anything that's still an issue should be filtering into this repo by now.
