### ISSUE TITLE
Rails 5 , require login error

### ISSUE THREAD

**Issue by navinspm** [Sorcery/sorcery#30]
I am trying to upgrade my rails version from 4.2 to 5.0, After upgrading rails version. I am facing this error 
`
Before process_action callback :require_login has not been defined`

This is my application_controller.rb code

` before_filter :require_login`

I am using sorcery 0.9.1.

**Comment by athix** [comment]
Hi @navinspm, this is probably because before_filter has been completely deprecated in Rails 5 iirc. We're releasing version 0.10.0 this friday, which should have full Rails 5 support. For now you can point your gemfile to use `github: 'Sorcery/sorcery'` if you need this fixed immediately.

**Comment by andey** [comment]
please add this to the README, for people doing the rails 5 upgrades

**Comment by andey** [comment]
`GIT
  remote: git://github.com/Sorcery/sorcery.git
  revision: fd48d561264e6560cd5ae3bdb135e4f70678c65e
  specs:
    sorcery (0.10.2)
      bcrypt (~> 3.1)
      oauth (~> 0.4, >= 0.4.4)
      oauth2 (~> 1.0, >= 0.8.0)`

And i'm still getting 

`/home/andey/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/callbacks.rb:641:in `block (2 levels) in skip_callback': Before process_action callback :require_login has not been defined (ArgumentError)`

on boot

**Comment by murtali** [comment]
@athix 

This issue has come up for me while upgrade from rails 4.2 to 5.0 -- I'm using the latest 0.15 version of sorcery but still seeing the:
```
skip_before_action :require_login, only: [:new]

# causing this error:
Before process_action callback :require_login has not been defined (ArgumentError)
```

The issue only comes up in production where config.eager_load = true -- 
some relevant github issues / stackoverflow questions suggest doing:

```
skip_before_action :require_login, raise: false
```

but this doesn't seem quite right to me. Is there some gotcha configuration or loading issue that changed between gem support from 4.2 to 5.0?

Thank for your help and continued support of this gem!
