### ISSUE TITLE
Using Okta as external provider causes NameError exception (for Oktum)

### ISSUE THREAD

**Issue by epdejager** [Sorcery/sorcery#306]
Please complete all sections.

### Configuration

- Sorcery Version: `0.16.2`
- Ruby Version: `2.7.2`
- Framework: `Rails 5.2.5`
- Platform: `macOS mojave 10.14.6`

### Expected Behavior

Listing Okta as an external provider should work: `config.external_providers = [:okta]`

### Actual Behavior

We get an exception: 
```
NameError:
  uninitialized constant Sorcery::Providers::Oktum
```
### Steps to Reproduce

Just try using okta as an external provider, and then run your specs.

### PR that Fixes this:
https://github.com/Sorcery/sorcery/pull/305/files

**Comment by athix** [comment]
Should be fixed in 0.16.3 which was just released, feel free to reopen if this is still an issue!
