### ISSUE TITLE
Brute force protection failed_logins_count incremented by 2

### ISSUE THREAD

**Issue by ophilbert** [Sorcery/sorcery#309]
Hello

### Configuration

Sorcery (0.16.3)
Ruby 3.0
Rails 7.0.2.3
MacOS

### Context

[Brute Force Protection wiki](https://github.com/Sorcery/sorcery/wiki/Brute-force-protection) states that the controller should call `user.register_failed_login!` to increase failed_login_count for user.

It seems to me that a failed login method already handle that. Maybe there's something I didn't understand. I followed the wiki instructions though. Maybe it needs an update or a clarification ?

### Expected Behavior

Failed login attempt should increase failed_logins_count by 1

### Actual Behavior

Failed login attempt increase failed_logins_count by 2

### Steps to Reproduce

1. Clone the [example repo here](https://github.com/ophilbert/sorcery_brute_force_issue)
2. Start the server
3. Create a user with email and password
4. Login with that user but provide a wrong password
5. See that 1 failed login is considered as 2 login attempts
6. Comment `user.register_failed_login!` in  `user_sessions_controller.rb `
7. Login with that user but provide a wrong password
8. See that 1 failed login, is considered as 1 login attempt 

Thanks for your help

**Comment by ophilbert** [comment]
I see ! The wiki is to blame then. Thanks for taking the time to review this issue.

**Comment by willnet** [comment]
I have corrected [the wiki](https://github.com/Sorcery/sorcery/wiki/Brute-force-protection). Thank you!
