### ISSUE TITLE
Using sorcery in an API-only rails app does not work

### ISSUE THREAD

**Issue by TheNeikos** [Sorcery/sorcery#330]
### Configuration

- Sorcery Version: `0.16.4`
- Ruby Version: `3.1.2`
- Framework: `rails-7`
- Platform: `linux-64_86`

### Expected Behavior

Sorcery should work out of the box with an API-only rails app

### Actual Behavior

It errors with `undefined local variable or method 'form_authenticity_token'`.

### Steps to Reproduce

1. Make a rails API app
2. Install sorcery
3. Call `login`

**Comment by mladenilic** [comment]
Login method calls `form_authenticity_token` which is defined in request forgery protection concern. You can include it with:
```
include ActionController::RequestForgeryProtection
```

**Comment by Nitrodist** [comment]
@mladenilic saved me some work here, thanks!
