### ISSUE TITLE
External Sub Module: create_from(provider) method

### ISSUE THREAD

**Issue by nsantiago2719** [Sorcery/sorcery#34]
@athix  here I have created a new issue as you told.  I have been wondering about this issue because if someone create an account using x.yz@gmail.com then they login through oauth, rather than getting them logged in Sorcery will create a new account **if google will give the xyz@gmail.com** because Sorcery treat those emails different right.

cc: @Ch4s3

**Comment by nsantiago2719** [comment]
Yes. By the way in number 2 rather than create account I prefer log in. But well the result will be the same I think where it will create a new account for the same email.

**Comment by athix** [comment]
Personally, I think this is a non-issue because there is no way to stop users from using the same email for different accounts if they wanted to. For example:

I own a domain with email support (mydomain.com) and have my personal gmail account (example@gmail.com). I can then use my personal email to create an account, and use any number of forwarding addresses (example@mydomain.com, example123@mydomain.com, etc) to create additional accounts. All of these accounts would technically be using the same email, but the app would treat them as being separate.

**Comment by nsantiago2719** [comment]
You have a point in that. But isn't it better if Sorcery can still differentiate if the email gave by google is already registered if they are registering or logging in through google oauth? This is just my point of view because sometimes persons get confused on multiple accounts.  And well this would be only applied in `create_from(provider)` method for google ouath.

**Comment by athix** [comment]
I think that functionality would be cool, but unless I'm mistaken, it's not as easy as just overwriting the create_from(provider) method for google. It should also be possible to modify the workflow of the application to support this functionality without too much effort. Would something like this work?

### User has no account

1) User attempts to login via google oauth (johnsmith@gmail.com)
2) In controller, searches for any users with the same email as what's provided by google
3) No users are found, calls create_from(provider) and continues

### User already has account (john.smith@gmail.com)

1) User attempts to login via google oauth (johnsmith@gmail.com)
2) In controller, searches for users with the same email, and finds a matching email (`@user`)
3) Creates new authentication record pointing at `@user ` and updates any missing fields on `@user` with mapped fields from oauth, then continues

Optionally for 3, instead redirect to another controller method which allows the user to decide what to do next.

@nsantiago2719, what do you think?

**Comment by nsantiago2719** [comment]
@athix I agree on you about overwriting the create_from(provider) method. Those are great idea on how to solve the issue. Will close this issue already.
