### ISSUE TITLE
Rails 7.1 support

### ISSUE THREAD

**Issue by simchikoops** [Sorcery/sorcery#349]
### Configuration

- Sorcery Version: `2.0.9`
- Ruby Version: `3.2.2`
- Framework: `Rails`
- Platform: `Mac`

### Expected Behavior

Generator 

Generator should run successfully.

### Actual Behavior

`/Users/koops/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0.rc1/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `timestamped_migrations' for ActiveRecord::Base:Class (NoMethodError)
	from /Users/koops/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorcery-0.16.5/lib/generators/sorcery/install_generator.rb:78:in `next_migration_number'
	from /Users/koops/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0.rc1/lib/rails/generators/migration.rb:43:in `set_migration_assigns!'
	from /Users/koops/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0.rc1/lib/rails/generators/migration.rb:59:in `migration_template'
	from /Users/koops/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorcery-0.16.5/lib/generators/sorcery/install_generator.rb:65:in `copy_migration_files'
`

### Steps to Reproduce

1. Run `rails generate sorcery:install`

**Comment by whyczz** [comment]
I got the same issue:

```
➜ rails g sorcery:install
      create  config/initializers/sorcery.rb
    generate  model User --skip-migration
       rails  generate model User --skip-migration 
      invoke  active_record
      create    app/models/user.rb
      invoke    test_unit
      create      test/models/user_test.rb
      create      test/fixtures/users.yml
      insert  app/models/user.rb
File unchanged! Either the supplied flag value not found or the content has already been inserted!  app/models/user.rb
/Users/a/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.0/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `timestamped_migrations' for ActiveRecord::Base:Class (NoMethodError)
	from /Users/a/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorcery-0.16.5/lib/generators/sorcery/install_generator.rb:78:in `next_migration_number'
	from /Users/a/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/generators/migration.rb:43:in `set_migration_assigns!'
	from /Users/a/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.0/lib/rails/generators/migration.rb:59:in `migration_template'
	from /Users/a/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorcery-0.16.5/lib/generators/sorcery/install_generator.rb:65:in `copy_migration_files'
```

It seems that 'timestamped_migrations' is [deprecated/removed](https://apidock.com/rails/ActiveRecord/Base/timestamped_migrations/class) as of rails 5.

That happens in the [install generator](https://github.com/Sorcery/sorcery/blob/master/lib/generators/sorcery/install_generator.rb#L78).  

### GUESSES
Closest thing I can find is a configuration value [of the same name](https://guides.rubyonrails.org/configuring.html#config-active-record-timestamped-migrations)

So a change to that should be the fix?

**Comment by r3id** [comment]
I am getting a similar issue when I run `rails generate sorcery:install user_activation reset_password session_timeout`

I am getting the following error...

```
.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.2/lib/rails.rb:51:in `configuration': undefined method `config' for nil:NilClass (NoMethodError)

      application.config
                 ^^^^^^^
```

Looking in my `application.rb` I have added the following to stop generating unit tests, maybe this is preventing the RSpec ones generating too?

```
# Don't generate system test files.
    config.generators.system_tests = nil
```
