### ISSUE TITLE
Error: Undefined method `authenticates_with_sorcery!' for User:Class

### ISSUE THREAD

**Issue by sarnold04** [Sorcery/sorcery#35]
I get the "Undefined method `authenticates_with_sorcery!' for User:Class" error in Rails 5.0.1 with Mongoid 6.0.3 and Sorcery 0.10.0. I added the authenticates_with_sorcery! beneath the includes in my model but still getting the error. As long as I use Rails 5.0.1, Mongoid 6.0.3 and Sorcery 0.9.1 it works fine. Is there any change I have to make with loading the functions?

Regards,
Sven

**Comment by athix** [comment]
Hi @sarnold04, do you use just `gem 'sorcery'` or do you also use `gem 'sorcery_mongoid'`? I don't think @Ch4s3 or myself use mongoid, so it probably just got overlooked.

If it helps, this is what my user model looks like in Rails 5:

```ruby
class User < ApplicationRecord
  authenticates_with_sorcery!
  ...
end
```

Thanks!

**Comment by sarnold04** [comment]
Hey athix,

my user model looks like this in Rails 5

```
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  authenticates_with_sorcery!
  ...
end
```

In my Gemfile if I use mongoid 6.0.3 and sorcery 0.9.1 it works fine but if I upgrade to 0.10.0 it crashes with the error mentioned above.

Regards,
Sven

**Comment by athix** [comment]
I imagine what happened is the logic for mongoid got extracted out into the `sorcery_mongoid` gem between `0.9.x` and `0.10.x`. Looking at the repo for it though, I'm not sure it actually works. Try including `gem 'sorcery_mongoid'` in your gemfile as well, and let me know if that works. If it doesn't, please post the full stack trace to help track down the exact cause.

**Comment by rjurado01** [comment]
I have the same error:

```
NoMethodError: undefined method `authenticates_with_sorcery!' for User:Class
from ~/rails/app/models/user.rb:3:in `<class:User>'
from ~/rails/app/models/user.rb:1:in `<top (required)>'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:477:in `load'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:477:in `block in load_file'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:662:in `new_constants_in'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:476:in `load_file'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:375:in `block in require_or_load'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:37:in `load_interlock'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:358:in `require_or_load'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:511:in `load_missing_constant'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:203:in `const_missing'
from (irb):1
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.1/lib/rails/commands/console.rb:65:in `start'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.1/lib/rails/commands/console_helper.rb:9:in `start'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
from ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
from bin/rails:4:in `require'
```

```ruby
#app/models/user.rb
class User
  include Mongoid::Document
  authenticates_with_sorcery!
end
```

```ruby
#config/initializers/sorcery.rb
Rails.application.config.sorcery.submodules = []

Rails.application.config.sorcery.configure do |config|

  config.user_config do |user|
  end

  config.user_class = 'User'
end
```

@athix sourcery_mongoid is not updated from three years ago and it doen't exist in rubygems.

**Comment by nsantiago2719** [comment]
@rjurado01 try moving `gem 'sorcery'` after `gem 'mongoid'` i had encountered this problem before and by adding gem mongoid before sorcery works for me.

**Comment by athix** [comment]
@rjurado01, @sarnold04

Ahha, this might only be a part of the problem, but I ran into something similar when implementing Sorcery on my personal app. You can't pass strings to the user_class config, it must be the class itself.

Ex: `config.user_class = User`

Instead of `config.user_class = 'User'`

Let me know how this turns out! I'll see about adding this to the documentation or updating the code to accept strings as well as the class object.

**Comment by rjurado01** [comment]
@athix Sorcery uses string when generates configuration file.

I have upload a repository to reproduce the error: https://github.com/rjurado01/sorcery-mongoid-error

**Comment by athix** [comment]
Thanks @rjurado01! I'll clone and check it out when I get a chance.

**Comment by SeanLuckett** [comment]
The above fix:
`config.user_class = User` in Sorcery config file 

also works for the same problem with Rails 5.1 and ActiveRecord. However, Sorcery `0.11.0` also generates the line with `config.user_class = 'User'`
