### ISSUE TITLE
generate sorcery:install fails because of depricated function "timestamped_migrations"

### ISSUE THREAD

**Issue by psal0** [Sorcery/sorcery#353]
### Configuration

- Sorcery Version: `0.16.5`
- Ruby Version: `3.2.2`
- Framework: `Rails 7.1.1`
- Platform: `MacOSX Arm64`

### Expected Behavior

'rails generate sorcery:install' should run through without any errors 

### Actual Behavior

The install script stops at creating the user migration. The error is:

´´´
Users/me/.frum/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-7.1.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `timestamped_migrations' for ActiveRecord::Base:Class (NoMethodError)
´´´

Issue is that the function used in the install has been deprecated for quite some time:
https://apidock.com/rails/ActiveRecord/Base/timestamped_migrations/class

My quick fix:

In sorcery-0.16.5/lib/generators/sorcery/install_generator.rb:
´´´
     private
      
      def self.next_migration_number(dirname)
        sleep 1 # make sure each time we get a different timestamp
        Time.now.utc.strftime('%Y%m%d%H%M%S')
      end
´´´

### Steps to Reproduce

Follow install instructions as described here on GitHub
1. install fresh rails 7.1.1 app 
2. add 'gem 'sorcery'' to the Gemfile
3. run 'bundle install'
4. run 'rails g sorcery:install'

**Comment by Spone** [comment]
Fixed by https://github.com/Sorcery/sorcery/pull/352

**Comment by r3id** [comment]
When is this getting merged?
