### ISSUE TITLE
rails generate sorcery:install not working

### ISSUE THREAD

**Issue by pama** [Sorcery/sorcery#38]
I tried from v0.10.2 till v0.9.1 with rails 5.0.1 and its not working. The command doesn't return to the terminal.

**Comment by Ch4s3** [comment]
Is there any output at all?

**Comment by pama** [comment]
@Ch4s3 I had no input output at all, 100% frozen. I tried other ruby version and worked, but not with Ruby 2.3.3

I realised that was Spring fault. I had to stop it. It wasn't easy to spot that one.

**Comment by Ch4s3** [comment]
:) Ahh spring! I was just going to ask if you were running spring. Glad it worked, and please do let us know if you have any issues, questions, or suggestions!
