### ISSUE TITLE
Move and/or merge existing pull requests

### ISSUE THREAD

**Issue by athix** [Sorcery/sorcery#4]
There's plenty of open pull requests on `NoamB/sorcery`. We can either merge them on `NoamB/sorcery` and then pull the commits directly onto `Sorcery/sorcery`, or encourage moving the PR to `Sorcery/sorcery` and merging there instead. If we mix and match however, there's bound to be a history conflict and the `Sorcery/sorcery` history would get a bit messy with merging `NoamB/sorcery` onto `Sorcery/sorcery` multiple times; so we should probably choose one of the two options and proceed with that method only.

**Comment by Ch4s3** [comment]
I would be in favor of moving the ones that seem more or less ready to go.

**Comment by Ch4s3** [comment]
Lets try to keep track and close them on the other side as we move them over.

**Comment by athix** [comment]
Looks like this might solve some twitter issues: [#719](https://github.com/NoamB/sorcery/pull/719)
