### ISSUE TITLE
Memory consumption problem

### ISSUE THREAD

**Issue by gogainda** [Sorcery/sorcery#42]
Based on result from 
`
CUT_OFF=1 bundle exec derailed bundle:mem
`
it takes 6 megabytes to load this gem
`
sorcery: 6.1797 MiB (Also required by: sorcery/engine)
    sorcery/protocols/oauth2: 2.5352 MiB
      oauth2: 2.5352 MiB
        oauth2/client: 1.1797 MiB
        oauth2/response: 1.1055 MiB
`
If I am not using oauth2 gem still load it into memory.
Can we drop this forced dependency on oauth2?

**Comment by athix** [comment]
We currently plan on moving the oauth dependencies out so it's only included if you use the external module. Unfortunately, until then we can't drop it without breaking the external submodule. As a temporary work-around, you might be able to fork sorcery and completely remove the external submodule and oauth/oauth2 dependencies. If you run into any problems with this, let me know!
