### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by athix** [Sorcery/sorcery#43]
While working on my personal site, I've noticed several spots where the documentation is starting to show its age. Opening this ticket to remind myself to go back and update it / discuss any issues that may arise. Also, while each individual module seems to be well documented, there doesn't seem to be a general "get started" article yet; I'm thinking about creating that with the assumption of an app that has all submodules enabled.

**Comment by athix** [comment]
TODO/Plans:
- [ ] Add build_from(provider)
- [ ] Complete auth flow for personal app
- [ ] Create rspec suite for personal app
- [ ] Update example app for rails 5 and new best practices
- [ ] Refactor Sorcery rspec suite & use new example app to replace existing rspec app (maybe?)
- [ ] Update wiki to match example app

**Comment by athix** [comment]
If anyone has some spare time and would like to help with this, I would greatly appreciate it.

**Comment by mladenilic** [comment]
Both the sample app and documentation are still suggesting `form_for`/`form_tag` over `form_with`. I guess this is one of the things that can go under the _rails 5 best practices_. 

I can help with this one, but I'd like to setup simple dev env (docker), to make it easier to run and test changes to the sample app. Let me know what do you think?

**Comment by athix** [comment]
@mladenilic I'd like to keep the example app as usage agnostic as possible, but getting it up-to-date is more important IMO. Feel free to modify as you see fit, and I can help review it as time permits.

**Comment by athix** [comment]
Seeing as we'll be dropping Rails 4 support in the not-so-distant future, I think it would also be reasonable to update any documentation to use whatever the Rails 5 standards are. No need to separate it into a different document.

**Comment by mladenilic** [comment]
@athix I opened couple of PRs on the sample app, I guess we can discuss it there.

> No need to separate it into a different document.

Sorry, I wasn't being clear here. I was referring to your `Update example app for rails 5 and new best practices` task in the message above, not the new documentation page.

**Comment by athix** [comment]
The documentation definitely still needs a lot of love, but I don't think this issue is necessary. Closing it out...
