### ISSUE TITLE
How can I get access_token in using github aouth?

### ISSUE THREAD

**Issue by tackeyy** [Sorcery/sorcery#44]
Can I get GitHub's ` access_token ` , when I use GitHub aouth External with?

I've checked Sorcery handles GitHub's ` access token ` as ` access_token. `
Is there any option or idea that gets Gitbub's ` access_token ` ?

**Comment by athix** [comment]
Hey @tackeyy, think I might have found what you're looking for by accident! If you call `sorcery_fetch_user_hash(provider)` inside your callback function, it should populate `@access_token`, which I think should have what you're looking for (assuming the callback is coming from github).

**Comment by tackeyy** [comment]
@athix Thanks for reply!
As you said, I can access Github's ` access_token ` .
I changed callback function like this.

```
    @user = create_from(provider)

    sorcery_fetch_user_hash(provider)
    @user.token = @access_token.token
    @user.save
```

It seems to not be smart,It seems to not be smart, because SQL query runs 2 times(create and update), but I achieved my goal, so I close this issue.

Thank you!

**Comment by athix** [comment]
@tackeyy no problem! You should be able to make it more efficient by only calling `sorcery_fetch_user_hash` and then creating the user using @user_hash and @access_token together. That said, having a `build_from(provider)` function seems like it'd be really useful both for your use-case, and the one I ran in to.

Glad this solved your issue. :)

**Comment by tackeyy** [comment]
@athix Thanks for the tips.
I updated callback function like this.
I think this code is what you told me.

It is better than before :)

```
    sorcery_fetch_user_hash(provider)
    @user = User.create(
      name: @user_hash[:user_info]['name'],
      email: @user_hash[:user_info]['email'],
      token: @user_hash[:token]
    )
```

>  having a build_from(provider) function seems like it'd be really useful
This means that having a build_from(provider) function in Sorcery, right?

**Comment by athix** [comment]
> This means that having a build_from(provider) function in Sorcery, right?

Yeah, currently you can only create users via Sorcery, seems odd that there isn't a build function as well. I'll probably try and implement one in the next couple weeks to make auth flow a bit easier for applications that can't always create users with only what's provided by oauth.
