### ISSUE TITLE
Could you move `login_lock!` out of protected

### ISSUE THREAD

**Issue by itay-grudev** [Sorcery/sorcery#46]
Could you move `login_lock!` out of protected like `login_unlock!`. It's quite useful for testing purposes and invoking it with send is rather ugly.

**Comment by itay-grudev** [comment]
Besides we can use this feature of the library to lock a user manually. It may also be useful to have an argument for explicitly setting a lock duration and/or infinity.

**Comment by ebihara99999** [comment]
For a testing purpose, i personally think It's better to implement `login_lock!` as a test helper than moving `login_lock!` out of protected. 
> Besides we can use this feature of the library to lock a user manually. It may also be useful to have an argument for explicitly setting a lock duration or infinity.
Would you tell me the use case? I guess you want to manage locked status of users independently for some reasons, for example, user A: locked( because the user broke terms of service ), user B: unlocked. Then, `login_lock!` is against brute_force_protection, and the use case is different from intention. It might be a good idea to implement manual user lock status and the management feature.

**Comment by Ch4s3** [comment]
@itay-grudev if you could clarify re: @ebihara99999's question, I'll take a look.

**Comment by itay-grudev** [comment]
The login `login_lock!` method's visibility scope is `protected` and cannot be used externally. The reason why I need it is for testing.

**Comment by itay-grudev** [comment]
But also because it may be useful for purposes other than testing moving it out of the protected scope may be more useful than making a `login_lock!` test helper.

**Comment by itay-grudev** [comment]
@ebihara99999 One may have some other method of detecting fraudulent login attempts and may want to lock a certain user manually.

**Comment by ebihara99999** [comment]
@itay-grudev Sorry it's been too long. For the testing purpose, as I said, it would be better to implement a test helper method. But it seems reasonable to need `#login_lock` for the general use, not only for brute force protection.
In this case, it's necessary to add or refactoring existing one into a lockable module like devise, and I don't know how much time to need...
What do you think, @Ch4s3 ? Need to add this feature to [the load map?](https://github.com/Sorcery/sorcery/issues/32)

**Comment by ebihara99999** [comment]
@Ch4s3
No discussion has been updated recently, and the subject seems fully discussed.
I think it would be better to close this.

**Comment by Ch4s3** [comment]
I'm going to close this, but would reopen it if people are still interested.
