### ISSUE TITLE
Is it fine to add undocumented option to initializer.rb?

### ISSUE THREAD

**Issue by tackeyy** [Sorcery/sorcery#48]
As I found the undocumented option which is about Github's [scope](https://developer.github.com/v3/oauth/#scopes) with external module in Github OAuth. I think it is better if below code is inserted in  [initializer.rb](https://github.com/Sorcery/sorcery/blob/master/lib/generators/sorcery/templates/initializer.rb#L114), because it takes time to find the option out if someone who uses Github OAuth with external module and want to manage the Github's scope.

> config.github.scope = 'user, repo'

**Comment by athix** [comment]
I don't see any problem adding the scope to the generators, personally. Adding a note above the Github values though saying why/how to use the scope would help users understand why it's there (and why or why not they should use it). Feel free to open a PR, where we can discuss the finer details.

Also, if you wanted to update the docs in the wiki at all your help would be greatly appreciated. :)

**Comment by tackeyy** [comment]
Thank you for the reply. As I opened PR #50, I close this issue.
