### ISSUE TITLE
Facebook as an external provider not including user info as defined in user_info_mapping.

### ISSUE THREAD

**Issue by mikemerritt** [Sorcery/sorcery#62]
I am trying to set up external providers in my app. I have followed the guide listed here: https://github.com/Sorcery/sorcery/wiki/External

Google works fine and I receive the email as requested. However when trying Facebook the data is not being received from Facebook. I have checked the @user_hash and it seems it's only including "name" and "id".

This is what my Sorcery config looks like.

```ruby
config.external_providers = %i[facebook google]

config.facebook.key = Rails.application.secrets.facebook_app_id
config.facebook.secret = Rails.application.secrets.facebook_app_secret
config.facebook.callback_url = "#{ENV['WEB_URL']}/oauth/callback?provider=facebook"
config.facebook.user_info_mapping = { email: 'email', first_name: 'first_name', last_name: 'last_name' }
config.facebook.scope = 'email'
config.facebook.display = 'page'

config.google.key = Rails.application.secrets.google_client_id
config.google.secret = Rails.application.secrets.google_client_secret
config.google.callback_url = "#{ENV['WEB_URL']}/oauth/callback?provider=google"
config.google.user_info_mapping = { email: 'email' }
```
And this is what my oauths controller looks like.

```ruby
class OauthsController < ApplicationController
  skip_before_action :require_login

  def oauth
    login_at(params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    if @user = login_from(provider)
      redirect_to root_path
    else
      @user = create_from(provider)
      @user.activate!
      reset_session
      auto_login(@user)
      redirect_to root_path
    end
  end

  private

  def auth_params
    params.permit(:code, :provider)
  end
end
```

**Comment by mikemerritt** [comment]
Solved by adding this to my config
```ruby
config.facebook.user_info_path = 'me?fields=email,first_name,last_name'
```

This should probably be mentioned in the documentation.

**Comment by athix** [comment]
Yeah, documentation is a little all over the place right now. If it's not already, we should add a note to the default config, as well as mention it in the wiki wherever facebook is mentioned. (External and Getting Started are the only ones I think)

If you want to update the documentation and config generator, we would definitely appreciate the help. Otherwise I'll try to get this in when I have some time to work on Sorcery.

**Comment by mikemerritt** [comment]
@athix Updated the config generator in this PR: https://github.com/Sorcery/sorcery/pull/63

**Comment by athix** [comment]
Thanks! Merged into master.
