### ISSUE TITLE
Conditional validation does not work with Rails 5 

### ISSUE THREAD

**Issue by Flyte22** [Sorcery/sorcery#66]
Hi,

the validation does not seem to work (using Rails 5.1.1) as described in the Wiki:

```ruby
validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
```

Whenever i update the password, the validation gets skipped silently.

After i changed it to this, it works:
```ruby
validates :password, length: { minimum: 3 }, if: -> { new_record? || :crypted_password_changed? }
validates :password, confirmation: true, if: -> { new_record? || :crypted_password_changed? }
validates :password_confirmation, presence: true, if: -> { new_record? || :crypted_password_changed? }
```

Does anyone know about this?

**Comment by ebihara99999** [comment]
Would you tell me where `#crypted_password_changed?` is defined? I can't fine the method in the Sorcery project.

**Comment by Flyte22** [comment]
Yes right, it's a Active Model Dirty-method, see http://api.rubyonrails.org/classes/ActiveModel/Dirty.html

**Comment by akinrt** [comment]
@Flyte22 can you please try running `:crypted_password_changed? || "you won't see me"` on pry or irb.
`:crypted_password_changed?` returns `:crypted_password_changed?` and worked on the if condition as well.
because `:crypted_password_changed?` is a symbol.

i think the following part in the [wiki](https://github.com/Sorcery/sorcery/wiki/Simple-Password-Authentication) is correct.

```ruby
# app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end
```

**Comment by athix** [comment]
The validation seems to work on my personal site using Rails 5, so I think this is an issue somewhere else; It could be that the password isn't actually being changed.

@Flyte22 could you please post the update and params methods from your User controller so we can get a better look?

Thanks!

**Comment by athix** [comment]
Closing this to clean out old issues without any movement.
