### ISSUE TITLE
login(params[:email], params[:password]) return nil

### ISSUE THREAD

**Issue by nghialuutrung** [Sorcery/sorcery#73]
In class SessionsController, i use login(params[:email], params[:password]) and funtion return nil, but database, email have exits.
And in database,  i querry. User is returned.

**Comment by ebihara99999** [comment]
Would you tell more information about the problem you encounterd like
* user model（or the other if you don't user User class for authentication）
* Sessions controller
* params sent to the session controller
* the data you use for login 
Given more information, I could give you some advice.

**Comment by nghialuutrung** [comment]
@ebihara99999 
user model
```
class User < ApplicationRecord
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end
end

```
sessions controller
```
class SessionsController < ApplicationController
  # skip_load_and_authorize_resource
  skip_before_action :require_login, except: [:destroy]

  def new
    redirect_to user_mypage_url(current_user) if logged_in?
  end

  def create
    if login(params[:email], params[:password])
      # remember_me!
      redirect_to user_mypage_url(current_user)
    else
      flash.now[:alert] = 'ログインに失敗しました。ログイン情報をお確かめください。'
      render :new
    end
  end

  def destroy
    # forget_me!
    logout
    redirect_to new_session_url, notice: 'ログアウトしました'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

```
the data you use for login: email and password

and when i checkout to before commit, i still can't login. I think my project is not wrong and gem has something wrong.

**Comment by ebihara99999** [comment]
Looking over your codes, you use User model but you pass Authentication model to config.authentications_class, and `#authenticates_with_sorcery!` doesn't receive block( [here is the definition](https://github.com/Sorcery/sorcery/blob/7c5fee441e03779ee2888ecef317440cd10a17e7/lib/sorcery/model.rb#L10)). 
Refactor codes with reference [wiki](https://github.com/Sorcery/sorcery/wiki/Simple-Password-Authentication). It will work!

**Comment by nghialuutrung** [comment]
@ebihara99999 
Thank you!

**Comment by athix** [comment]
Looks like this has been solved, please reopen if that's not the case.
