### ISSUE TITLE
Cannlot load such file bcrypt_ext - Windows 10 - ruby 2.3.3 - rails 5.1.2

### ISSUE THREAD

**Issue by ChrisKaun** [Sorcery/sorcery#75]
I've created a new rails application and added sorcery as a required gem to my gemfile.
When bundling and then trying to start the console I get the following error message:

```
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- bcrypt_ext (LoadError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
....
```

Googled a bit and it seems that bcrypt has a problem when installing the right version for windows.
For example see this [issue](https://github.com/codahale/bcrypt-ruby/issues/149).

Anyway to add this fix to the Sorcery dependencies?

**Comment by athix** [comment]
To be totally honest, trying to develop ruby on rails on windows will likely be quite the uphill battle. I would recommend switching to a unix platform if at all possible (or using a free VM service).

That said, have you tried following the process in that issue you found? Sorcery's gemspec is fuzzy locked to `~> 3.1`, so you may be able to use the fix they presented without altering Sorcery at all.

```ruby
# ./Gemfile
...
gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', require: 'bcrypt'
gem 'sorcery'
```

**Comment by ChrisKaun** [comment]
Well, stupid me. I've overread this comment and only tried the other suggestions.

**Comment by athix** [comment]
Haha, no problem. Glad I could help.

**Comment by TechiePriyaRanjan** [comment]
Thank you @athix . it worked 🎉
