### ISSUE TITLE
Upgrading from Rails 4.2.0 to 5.1.2 causes the following error:

### ISSUE THREAD

**Issue by bruparel** [Sorcery/sorcery#79]
Before process_action callback :require_login has not been defined.  Here is my HomeController:

class HomeController < ApplicationController
  # testing new keys
  skip_before_action :require_login, :only => [:index]
end

Here is the stack-trace:

ArgumentError - Before process_action callback :require_login has not been defined:
  activesupport (5.1.2) lib/active_support/callbacks.rb:710:in `block (2 levels) in skip_callback'
  activesupport (5.1.2) lib/active_support/callbacks.rb:706:in `block in skip_callback'
  activesupport (5.1.2) lib/active_support/callbacks.rb:622:in `block in __update_callbacks'
  activesupport (5.1.2) lib/active_support/callbacks.rb:620:in `__update_callbacks'
  activesupport (5.1.2) lib/active_support/callbacks.rb:705:in `skip_callback'
  actionpack (5.1.2) lib/abstract_controller/callbacks.rb:181:in `block (3 levels) in <module:ClassMethods>'
  actionpack (5.1.2) lib/abstract_controller/callbacks.rb:74:in `block in _insert_callbacks'
  actionpack (5.1.2) lib/abstract_controller/callbacks.rb:73:in `_insert_callbacks'
  actionpack (5.1.2) lib/abstract_controller/callbacks.rb:180:in `block (2 levels) in <module:ClassMethods>'
  app/controllers/home_controller.rb:3:in `<class:HomeController>'
  app/controllers/home_controller.rb:1:in `<top (required)>'

I am sure it is something basic that I do not know about Rails 5 upgrade.  Please advise

I am using the latest version of Sorcery as shown below:

Bharat:~/vgoffice_512  
→ gem list | grep sorcery
sorcery (0.11.0)

Bharat:~/vgoffice_512  

Thanks.

**Comment by athix** [comment]
This happens because you haven't defined `before_action :require_login` in your ApplicationController. See the [wiki](https://github.com/Sorcery/sorcery/wiki/Simple-Password-Authentication) for more details.
