### ISSUE TITLE
Redirect NoamB/sorcery to Sorcery/sorcery

### ISSUE THREAD

**Issue by athix** [Sorcery/sorcery#9]
NoamB/sorcery is probably going to be visited for a while after the transition, so having it link to the new repo would be preferable. I've opened a PR on NoamB/sorcery for this.

**Comment by Ch4s3** [comment]
Yeah, I still need @arnvald to give me access to the old repo.

**Comment by arnvald** [comment]
I've merged that PR.

@Ch4s3 I can't give access to old repo, I have write access there, but not admin access. I've given you the permission to rubygems though, so you can release gem now.
