### ISSUE TITLE
How to generate new session token

### ISSUE THREAD

**Issue by Sanjay-Chaudhary** [Sorcery/sorcery#92]
How to generate new session token for users upon authentication. When a user has logged in successfully after that how to create new session token.

**Comment by Ch4s3** [comment]
What is the use case here? I'm not quite sure what you need to do. Is the default session behavior not working for you?

**Comment by Sanjay-Chaudhary** [comment]
The point i am trying to raise here is does sorcery does not create a new session id once the user logs into the system after entering user id and password authentication. 
Does it not generate a new session_id value as part of the session token for users upon authentication. An attacker who could set the session token in a browser prior to logon may be able to hijack sessions of any user who logs in using that browser. 

Want to know if sorcery does this. If yes then how?
Or there is no such thing happens in sorcery.

**Comment by Ch4s3** [comment]
Sorry for the delay, I'll try to follow up soon.

**Comment by athix** [comment]
@mladenilic this would be a good issue to investigate further.

**Comment by mladenilic** [comment]
@athix Sorcery does reset the session on login. Here's the relevant code – https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/controller.rb#L53

After each login/logout new session id will be generated.

@Sanjay-Chaudhary I hope this answers your question.

**Comment by athix** [comment]
Closing this due to lack of movement, if anyone still has a session cookie related problem, please open a new issue with additional details. Thanks!
